These are the exercise problems from the book Python programming and Numerical methods book:

https://pythonnumericalmethods.berkeley.edu/notebooks/Index.html

# Chapter 5: Iteration

https://pythonnumericalmethods.berkeley.edu/notebooks/chapter05.04-Summary-and-Problems.html#problems

Only those problems that need to be solved in a notebook environment

1. What will the value of y be after the following code is executed?

In [1]:
# my estimate before executing the code is 1000 as a double loop looks at all possible iter values of the inner loop
# with each value in the outer loop and thus only one value at each run in outer loop will be equal to the inner loop 
y = 0
for i in range(1000):
    for j in range(1000):
        if i == j:
            y += 1

In [2]:
y

1000

2. Write a function my_max(x) to return the maximum (largest) value in x. Don’t use the built-in Python function max.

In [3]:
def my_max(x):

  largest_val = x[0]

  for val in x[1:]:
    if val > largest_val:
      largest_val = val
  
  return largest_val

In [4]:
# test case 1
print(my_max([4,8,9,10,1,4]))
print(max([4,8,9,10,1,4]))

10
10


3. Write a function my_n_max(x, n) to return a list consisting of the n largest elements of x. You may use Python’s max function. You may also assume that x is a one-dimensional list with no duplicate entries, and that n is strictly positive integer smaller than the length of x.

In [5]:
def my_n_max(x, n):

  n_max = []

  while len(n_max) < n:
    n_max.append(max(x))
    x.remove(max(x))

  return n_max

In [6]:
# test case 1
# Output = [10, 9, 8]
x = [7, 9, 10, 5, 8, 3, 4, 6, 2, 1]
out = my_n_max(x, 3)
print(out)

[10, 9, 8]


4. Let m be a matrix of positive integers. Write a function my_trig_odd_even(m) to return an array q, where q[i, j] = sin (m[i, j]) if m[i, j] is even, and q[i, j] = cos (m[i, j]) if m[i, j] is odd.

In [7]:
import numpy as np

def my_trig_odd_even(m):
  
  m = np.array(m, dtype = np.float64)

  sin_idxs = list(zip(np.where(m % 2 == 0)[0], np.where(m % 2 == 0)[1]))
  cos_idxs = list(zip(np.where(m % 2 == 1)[0], np.where(m % 2 == 1)[1]))
  
  for idx in sin_idxs:
    m[idx] = np.sin(m[idx])
  
  for idx in cos_idxs:
    m[idx] = np.cos(m[idx])

  return m

In [8]:
A = np.array([[1,3,2],[4,5,6],[7,8,9]])
my_trig_odd_even(A)

array([[ 0.54030231, -0.9899925 ,  0.90929743],
       [-0.7568025 ,  0.28366219, -0.2794155 ],
       [ 0.75390225,  0.98935825, -0.91113026]])

5. Let P be an mxp array and Q be a pxn array. As you will find later in this book, M=PxQ is defined as $M[i,j] = 𝝨_{k=1}^{p}P[i,k]*Q[k,j]$. Write a function my_mat_mult(P, Q) that uses for-loops to compute M, the matrix product of P and Q. 

__Hint:__ You may need up to three nested for-loops. Do not use the function np.dot.

In [9]:
# helper function for dot products
def dot_product(p, q):
  
  dot_prod = 0

  for idx in range(len(p)):
    dot_prod += p[idx]*q[idx]

  return dot_prod

def my_mat_mult(P,Q):

  # first we need to check whther no of columns of P equal the no of rows in Q for this to be a valid matrix multiplication
  if P.shape[1] != Q.shape[0]:
    print('Matrices cannot be multiplied.')
  
  else:

    # result of multiplying and m by n matrix to an n by p matrix is m by p
    # where m are the no of rows of first matrix and p are the no of columns in the second matrix
    final_mat = np.zeros((P.shape[0], Q.shape[1]))

    # we need to perform a dot product of each row in P with each column in Q
    for row in range(P.shape[0]):
      for col in range(Q.shape[1]):
        final_mat[row,col] = dot_product(P[row,:], Q[:,col])

    return final_mat

In [10]:
# test case 1
# Output:
#  array([[3., 3., 3.],
#        [3., 3., 3.],
#        [3., 3., 3.]])

P = np.ones((3, 3))
my_mat_mult(P, P)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [11]:
# test case 2
# Output:
# array([[30, 30, 30],
#       [70, 70, 70]])

P = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
Q = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4]])
my_mat_mult(P, Q)

array([[30., 30., 30.],
       [70., 70., 70.]])

6. The interest, i, on a principle, PO, is a payment for allowing the bank to use your money. Compound interest is accumulated according to the formula $𝑃_n = (1+i) P_{n−1}$, where n is the compounding period, usually in months or years. Write a function my_saving_plan(P0, i, goal) where the output is the number of years it will take 𝑃0 to become goal at i% interest compounded annually.

In [12]:
def my_saving_plan(P0, i, goal):
    
    years = 0

    while P0 < goal:
      P0 *= (1 + i)
      years += 1
    
    return years

In [13]:
# test case 1
# Output: 15
my_saving_plan(1000, 0.05, 2000)

15

In [14]:
# test case 2
# Output: 11
my_saving_plan(1000, 0.07, 2000)

11

In [15]:
# test case 3
# Output: 21
my_saving_plan(500, 0.07, 2000)

21

7. Write a function with my_find(M), where output is a list of indices i where M[i] is 1. You may assume that M is a list of only ones and zeros. Do not use the built-in Python function find.

In [16]:
def my_find(M):

  return [idx for idx in range(len(M)) if M[idx] == 1]

In [17]:
# test case 1
# Output: [0, 2, 3]
M = [1, 0, 1, 1, 0]

my_find(M)

[0, 2, 3]

8. Assume you are rolling two six-sided dice, each side having an equal chance of occurring. Write a function my_monopoly_dice(), where the output is the sum of the values of the two dice thrown but with the following extra rule: if the two dice rolls are the same, then another roll is made, and the new sum added to the running total. For example, if the two dice show 3 and 4, then the running total should be 7. If the two dice show 1 and 1, then the running total should be 2 plus the total of another throw. Rolls stop when the dice rolls are different.

In [18]:
def my_monopoly_dice():

  dice1 = np.random.randint(1,7)
  dice2 = np.random.randint(1,7)

  n_runs = 1
  running_total = dice1 + dice2
  print(f'First run: dice 1: {dice1}, dice 2: {dice2}. Running total: {running_total}')

  while dice1 == dice2:
    
    dice1 = np.random.randint(1,7)
    dice2 = np.random.randint(1,7)

    running_total += dice1 + dice2
    n_runs += 1
    print(f'Run {n_runs}: dice 1: {dice1}, dice 2: {dice2}. Running total: {running_total}')

  # if n_runs > 1:
  #   running_total += dice1 + dice2
  #   print(f'Final Run {n_runs}: dice 1 - {dice1}, dice 2 - {dice2}. Running total: {running_total}')

In [ ]:
my_monopoly_dice()

First run: dice 1: 1, dice 2: 1. Running total: 2
Run 2: dice 1: 1, dice 2: 4. Running total: 7


9. A number is prime if it is divisible without remainder only by itself and 1. The number 1 is not prime. Write a function my_is_prime(n), where output is 1 if n is prime and 0 otherwise. Assume that n is a strictly positive integer.

https://stackoverflow.com/questions/5811151/why-do-we-check-up-to-the-square-root-of-a-number-to-determine-if-the-number-is#:~:text=To%20test%20whether%20a%20number,square%20root%20of%20that%20number%3F&text=because%20if%20n%20%3D%20a*b,%3D%20a*b%20%3D%20n%20.&text=To%20clarify%2C%20this%20means%20we,floor(sqrt(n))%20.

In [19]:
import math

def my_is_prime(n):

  if n == 1:
    return 0

  # we only need to check till square root of n as if a number n has factors a and b both greater than 1 then
  # they cannot be both greater than square root of n as sqrt(n) * sqrt(n) = n. Thus, if both are greater than 
  # sqrt(n) then the number becomes bigger than n. So, a non prime number or composite number will have atleast 
  # one factor greater than 1 that is below or equal to sqrt(n)
  # link: stack overflow link provided above
  for num in range(2, math.floor(math.sqrt(n)) + 1):
    if n % num == 0:
      return 0

  return 1

In [20]:
# test case 1
# expected output: 1
my_is_prime(19)

1

In [21]:
# test case 2
# expected output: 1
my_is_prime(17)

1

In [22]:
# test case 3
# expected output: 0
my_is_prime(25)

0

10. Write a function my_n_primes(n) where primes is a list of the first n primes. Assume that n is a strictly positive integer.

In [23]:
def my_n_primes(n):

  prime_list = []

  for num in range(2,n):
    if my_is_prime(num):
      prime_list.append(num)

  return prime_list

In [24]:
my_n_primes(25)

[2, 3, 5, 7, 11, 13, 17, 19, 23]

In [25]:
my_n_primes(100)

[2,
 3,
 5,
 7,
 11,
 13,
 17,
 19,
 23,
 29,
 31,
 37,
 41,
 43,
 47,
 53,
 59,
 61,
 67,
 71,
 73,
 79,
 83,
 89,
 97]

11. Write a function my_n_fib_primes(n), where the output fib_primes is a list of the first n numbers that are both a Fibonacci number and prime. Note: 1 is not prime. Hint: Do not use the recursive implementation of Fibonacci numbers. A function to compute Fibonacci numbers is presented in Section 6.1. You may use the code freely.

In [26]:
# code for getting fibonacci number without recursion from Page 109 section 6.1 of the book.
def iter_fib(n):

  fib = np.ones(n)

  for i in range(2,n):
    fib[i] = fib[i-1] + fib[i-2]

  return fib

Testing the function

In [27]:
iter_fib(3)

array([1., 1., 2.])

In [28]:
iter_fib(5)

array([1., 1., 2., 3., 5.])

In [29]:
iter_fib(10)

array([ 1.,  1.,  2.,  3.,  5.,  8., 13., 21., 34., 55.])

In [30]:
def my_n_fib_primes(n):
    
    fib_primes = []
    n_fibonacci = n

    while len(fib_primes) < n:
      fib_numbers = np.array(iter_fib(3 + n_fibonacci)[3:], dtype = np.int64)
      primes = my_n_primes(fib_numbers[-1])
      fib_primes = fib_primes + list(set(fib_numbers).intersection(set(primes)))
      fib_primes = list(set(fib_primes))
      n_fibonacci += 1

    return sorted(fib_primes)

In [31]:
# test case 1
# Output: [3, 5, 13, 89, 233, 1597, 28657, 514229]
my_n_fib_primes(8)

[3, 5, 13, 89, 233, 1597, 28657, 514229]

In [32]:
# Output: [3, 5, 13]
my_n_fib_primes(3)

[3, 5, 13]

12. Write a function my_trig_odd_even(M), where the output Q[i,j] = sin(π/M[i,j]) if M[i,j] is odd, and Q[i,j] = cos(π/M[i,j]) if M[i,j] is even. Assume that M is a two-dimensional array of strictly positive integers.

In [35]:
def my_trig_odd_even(m):
  
  m = np.array(m, dtype = np.float64)

  sin_idxs = list(zip(np.where(m % 2 == 1)[0], np.where(m % 2 == 1)[1]))
  cos_idxs = list(zip(np.where(m % 2 == 0)[0], np.where(m % 2 == 0)[1]))
  
  for idx in sin_idxs:
    m[idx] = np.sin(np.pi/m[idx])
  
  for idx in cos_idxs:
    m[idx] = np.cos(np.pi/m[idx])

  return m

In [36]:
# test case
# Output: [[0.8660, 0.7071], [0.8660, 0.4339]]
M = [[3, 4], [6, 7]]
my_trig_odd_even(M)

array([[0.8660254 , 0.70710678],
       [0.8660254 , 0.43388374]])

13. Let 𝐶 be a square connectivity array containing zeros and ones. We say that point 𝑖 has a connection to point 𝑗, or 𝑖 is connected to 𝑗, if 𝐶[𝑖,𝑗]=1. Note that connections in this context are one-directional, meaning 𝐶[𝑖,𝑗] is not necessarily the same as 𝐶[𝑗,𝑖]. For example, think of a one-way street from point A to point B. If A is connected to B, then B is not necessarily connected to A.

Write a function my_connectivity_mat_2_dict(C, names), where C is a connectivity array and names is a list of strings that denote the name of a point. That is, names[i] is the name of the name of the i-th point.

The output variable node should be a dict with the key as the string in names and value is a vector containing the indices, j, such that 𝐶[𝑖,𝑗]=1. In other words, it is a list of points that point i is connected to.

In [37]:
C = [[0, 1, 0, 1], [1, 0, 0, 1], [0, 0, 0, 1], [1, 1, 1, 0]]
names = ['Los Angeles', 'New York', 'Miami', 'Dallas']

In [46]:
def my_connectivity_mat_2_dict(C, names):
  # we use idx + 1 as python is zero indexed and we want the exact location of connectivity
    node = {names[val]: [idx+1 for idx in range(len(C[val])) if C[val][idx] == 1] for val in range(len(names))}
    return node

In [47]:
# test case
# Output: node['Los Angeles'] = [2, 4]
#         node['New York'] = [1, 4]
#         node['Miami'] = [4]
#         node['Dallas'] = [1, 2, 3]

node = my_connectivity_mat_2_dict(C, names)
node

{'Los Angeles': [2, 4], 'New York': [1, 4], 'Miami': [4], 'Dallas': [1, 2, 3]}

14. Turn the list words of lower case characters to upper case using list comprehension.

In [48]:
words = ['test', 'data', 'analyze']
[word.upper() for word in words]

['TEST', 'DATA', 'ANALYZE']