These are the exercise problems from the book Python programming and Numerical methods book:

https://pythonnumericalmethods.berkeley.edu/notebooks/Index.html

# Exercise 1

Only those problems that need to be solved in a notebook environment

5. Compute the area of a triangle with base 10 and height 12. Recall that the area of a triangle is half the base times the height.

In [1]:
base = 10
height = 12

(1/2) * base * height

60.0

6. Compute the surface area and volume of a cylinder with radius 5 and height 3.

Volume of a cyclinder = $πr^2h$

Surface area of a cylinder = $2πrh + 2πr^2$

In [2]:
import math

radius = 5
height = 3
vol_cyclinder = math.pi * (radius**2) * height
sur_area = 2*math.pi*radius*height + 2*math.pi*(radius**2)

print(vol_cyclinder)
print(sur_area)

235.61944901923448
251.32741228718345


7.Compute the slope between the points (3,4)
 and (5,9). Recall that the slope between points (𝑥1,𝑦1)
 and (𝑥2,𝑦2) is $\frac{𝑦2−𝑦1}{𝑥2−𝑥1}$.

In [4]:
p1 = (3,4)
p2 = (5,9)

m = ( (p2[1] - p1[1])/ (p2[0] - p1[0]) )
m

2.5

8. Compute the distance between the points (3,4) and (5,9). Recall that the distance between points in two dimensions is $\sqrt{(x2 - x1)^2 + (y2-y1)^2}$.

In [5]:
p1 = (3,4)
p2 = (5,9)

dist = math.sqrt( (p2[1] - p1[1])**2 + (p2[0] - p1[0])**2 )
dist

5.385164807134504

9. Use Python’s factorial function to compute 6!

In [6]:
math.factorial(6)

720

10. A year is considered to be 365 days long. However, a more exact figure is 365.24 days. As a consequence, if we held to the standard 365-day year, we would gradually lose that fraction of the day over time, and seasons and other astronomical events would not occur as expected. A leap year is a year that has an extra day, February 29, to keep the timescale on track. Leap years occur on years that are exactly divisible by 4, unless it is exactly divisible by 100, unless it is divisible by 400. For example, the year 2004 is a leap year, the year 1900 is not a leap year, and the year 2000 is a leap year. Compute the number of leap years between the years 1500 and 2010.


Here's how the sequence works.

If a year is not divisible by 4 then it's not a leap year.

If a year is divisible by 4 then: <br>
- If the year is not divisible by 100, then its a leap year
- else if the year is divisible by 100, then its a leap year only if its also divisible by 400.

In [14]:
start_year = 1500
end_year = 2010
count_leaps = 0

# loop over years and move by 4 as 1500 is divisible by 4 and to be a leap year each year has to be divisible by 4
for year in range(start_year, end_year + 1, 4):
  
  # check if divisible by 4
  if year % 4 == 0:
    
    # if the year is not divisible by 100 then its a leap year
    if year % 100 != 0:
      print(f'{year} is divisble by 4 but not by 100 and thus is a leap year.')
      count_leaps += 1
    
    # if the year is divisible by 100 then it must also be divisible by 400 to be a leap year
    else:
      if year % 400 == 0:
        print(f'{year} is divisble by 4, and by 100 and also by 400 and thus is a leap year.')
        count_leaps += 1

print()
print(f'Total leap years between {start_year} and {end_year}: {count_leaps}')

1504 is divisble by 4 but not by 100 and thus is a leap year.
1508 is divisble by 4 but not by 100 and thus is a leap year.
1512 is divisble by 4 but not by 100 and thus is a leap year.
1516 is divisble by 4 but not by 100 and thus is a leap year.
1520 is divisble by 4 but not by 100 and thus is a leap year.
1524 is divisble by 4 but not by 100 and thus is a leap year.
1528 is divisble by 4 but not by 100 and thus is a leap year.
1532 is divisble by 4 but not by 100 and thus is a leap year.
1536 is divisble by 4 but not by 100 and thus is a leap year.
1540 is divisble by 4 but not by 100 and thus is a leap year.
1544 is divisble by 4 but not by 100 and thus is a leap year.
1548 is divisble by 4 but not by 100 and thus is a leap year.
1552 is divisble by 4 but not by 100 and thus is a leap year.
1556 is divisble by 4 but not by 100 and thus is a leap year.
1560 is divisble by 4 but not by 100 and thus is a leap year.
1564 is divisble by 4 but not by 100 and thus is a leap year.
1568 is 

11. A very powerful approximation for π was developed by a brilliant mathematician named Srinivasa Ramanujan. The approximation is the following:

$\frac{1}{𝜋} ≈ \frac{2\sqrt{2}}{\sqrt{9801}} Σ_{k=0}^{N} \frac{(4k)!(1103 + 26390k)}{(k!)^4 396^{4k}}$.

Use Ramanujan’s formula for 𝑁=0 and 𝑁=1 to approximate 𝜋. Be sure to use format long. Compare your approximation with Python’s stored value for pi. Hint: 0!=1 by definition.

In [26]:
N = 10

first_num = (2*math.sqrt(2))/9801
second_num = 0

for k in range(N):
  num = math.factorial(4*k) * (1103 + 26390*k)
  den = (math.factorial(k)**4) * (396)**(4*k) 
  second_num += (num/den)

pi = 1/(first_num * second_num)
pi  

3.141592653589793

In [23]:
math.pi

3.141592653589793

12. The __hyperbolic sin__ or __sinh__ is defined in terms of exponentials as $sinh(𝑥) = \frac{exp(𝑥)−exp(−𝑥)}{2}$. Compute __sinh__ for 𝑥=2 using exponentials. Verify that the result is indeed the __hyperbolic sin__ using Python’s function __sinh__ in the math module.

In [29]:
x = 2

(math.exp(x) - math.exp(-x))/2

3.626860407847019

In [30]:
math.sinh(x)

3.626860407847019

13. Verify that $sin^2x + cos^2x = 1$ for x = $π, \frac{π}{2}, \frac{π}{4}, \frac{π}{6}$. 

In [57]:
import sympy as sym
from IPython.display import display, Math

x = [math.pi, math.pi/2, math.pi/4, math.pi/6]
x_sym = [sym.pi, sym.pi/2, sym.pi/4, sym.pi/6]

for idx in range(len(x)):
  # print(f'sin^2(x) + cos^2(x) = {math.sin(x[idx])**2 + math.cos(x[idx])**2} for x = {x_sym[idx]}')
  display( Math('sin^2(x) + cos^2(x) = %s \\text{ for x } = %s' %((math.sin(x[idx])**2 + math.cos(x[idx])**2), sym.latex(x_sym[idx]))) )
  print()

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

14. Compute the sin 87°.

In [58]:
math.sin(87)

-0.8218178366308225

15. Write a Python statement that generates the following error:
“AttributeError: module ‘math’ has no attribute ‘sni’”
Hint: sni is a misspelling of the function sin.

In [63]:
math.sni(2)

AttributeError: ignored

16. Write a Python statement that generates the following error:
“TypeError: sin() takes exactly one argument (0 given)”
Hint: Input arguments refers to the input of a function (any function); for example, the input in 𝑠𝑖𝑛(𝑝𝑖/2) is 𝑝𝑖/2.

In [64]:
math.sin()

TypeError: ignored

17. If P is a logical expression, the law of noncontradiction states that P AND (NOT P) is always false. Verify this for P true and P false.

In [67]:
P_true = 2 == 1+1
P_false = 2 == 2+1

print(P_true and not P_true)
print(P_false and not P_false)

False
False


18. Let P and Q be logical expressions. De Morgan’s rule states that 

𝑁𝑂𝑇 (𝑃 𝑂𝑅 𝑄) = (𝑁𝑂𝑇 𝑃) 𝐴𝑁𝐷 (𝑁𝑂𝑇 𝑄) and <br>
𝑁𝑂𝑇 (𝑃 𝐴𝑁𝐷 𝑄) = (𝑁𝑂𝑇 𝑃) 𝑂𝑅 (𝑁𝑂𝑇 𝑄). 

Generate the truth tables for each statement to show that De Morgan’s rule is always true.

In [74]:
P = 2 == 1+1 # true statement
Q = 4+2 == 7 # false statement

# verifying de morgan's rule
print(not (P or Q) == (not P) & (not Q))
print(not (P & Q) == (not P) or (not Q))

True
True


In [90]:
# creating truth tables for P and Q
import numpy as np
import pandas as pd

arr = np.array([[P & Q, P & (not Q)], [not P & Q, not P & (not Q)]], dtype = int)
truth_table = pd.DataFrame(arr)

truth_table.index = pd.MultiIndex.from_tuples([('P', int(P)), ('P', int(not P))])
truth_table.columns = pd.MultiIndex.from_tuples([('Q', int(not Q)), ('Q', int(Q))])

truth_table

Q   
     1  0
P 1  0  1
  0  1  0

19. Under what conditions for 𝑃 and 𝑄 is (𝑃 𝐴𝑁𝐷 𝑄) 𝑂𝑅 (𝑃 𝐴𝑁𝐷 (𝑁𝑂𝑇 𝑄)) false?

In [92]:
# P as true and Q as false

P = 2 == 1+1 
Q = 4+2 == 7 

(P & Q) or (P & (not Q))

True

In [93]:
# P as true and Q as true

P = 2 == 1+1 
Q = 4+2 == 6

(P & Q) or (P & (not Q))

True

In [94]:
# P as false and Q as true

P = 2 == 1+2 
Q = 4+2 == 6

(P & Q) or (P & (not Q))

False

In [95]:
# P as false and Q as false

P = 2 == 1+2 
Q = 4+2 == 7

(P & Q) or (P & (not Q))

False

when P is false and Q is true or when both P and Q are false is (𝑃 𝐴𝑁𝐷 𝑄) 𝑂𝑅 (𝑃 𝐴𝑁𝐷 (𝑁𝑂𝑇 𝑄)) false.

### Logical gates refresher

https://www.geeksforgeeks.org/logic-gates-in-python/

quora question on equivalent logic for OR using AND and not:
https://www.quora.com/How-can-you-construct-an-equivalent-logical-expression-for-OR-using-only-AND-and-NOT-in-MatLab

20. Construct an equivalent logical expression for OR using only AND and NOT.

In [169]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [172]:
# extracting numbers divisible by either 3 or 4
np.where((arr % 3 == 0) | (arr % 4 == 0))

(array([0, 3, 4, 6, 8, 9]),)

From the quora post it's mentioned that NAND gate is equivalent to OR when using inverse inputs.

NAND stands for negative AND and returns 0 when both inputs are 1. (geeks for geeks blog referenced above). 

In [173]:
# code taken from: https://www.geeksforgeeks.org/logic-gates-in-python/
# only when one of the inputs are false we return 1
def NAND (a, b):
    if a == 1 and b == 1:
        return False
    else:
        return True

In [177]:
# replicating OR using NAND. Previously we used or filter values dividible by 3 or 4.
# Here, inverse inputs would mean value not divisible by 3 and 4, which means val % 3 != 0 and val % 4 != 0
logic = [NAND(val % 3 != 0, val % 4 != 0) for val in arr]
arr[np.where(np.array(logic) == 1)[0]]

array([0, 3, 4, 6, 8, 9])

21. Construct an equivalent logical expression for AND using only OR and NOT.

Similarly, equivalent of AND is NOR or negative OR when using inverse inputs. (quora post referenced above)

In [178]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [179]:
# filtering values between 2 and 7 (inclusive)
np.where((arr >= 2) & (arr <= 7))

(array([2, 3, 4, 5, 6, 7]),)

In [180]:
# code for NOR taken from: https://www.geeksforgeeks.org/logic-gates-in-python/
# only when both inputs are false we return the value as 1 else all are 0
def NOR(a, b):
    if(a == 0) and (b == 0):
        return 1
    elif(a == 0) and (b == 1):
        return 0
    elif(a == 1) and (b == 0):
        return 0
    elif(a == 1) and (b == 1):
        return 0

In [181]:
# providing inverted inputs for NAND, which is val < 2 and val > 7. only where both are false we return True
logic = [NOR(val < 2, val > 7) for val in arr]
arr[np.where(np.array(logic) == 1)[0]]

array([2, 3, 4, 5, 6, 7])

22. The logical operator XOR has the following truth table:
Construct an equivalent logical expression for XOR using only AND, OR, and NOT that has the same truth table (see the following figure) 

figure is in the text link provided at the start of the notebook.

XOR simply means where logic a and b are different.

In other words True and True should return False and False and False should return False.

True and False would return True, False and True would return True.

In [187]:
arr = np.array([[1 & (not 1), 1 | 0], [0 | 1, not 1 & (not 0)]], dtype = int)
truth_table = pd.DataFrame(arr)

truth_table.index = pd.MultiIndex.from_tuples([('P', 1), ('P', 0)])
truth_table.columns = pd.MultiIndex.from_tuples([('Q', 1), ('Q', 0)])

truth_table

Q   
     1  0
P 1  0  1
  0  1  0