These are the exercise problems from the book Python programming and Numerical methods book:

https://pythonnumericalmethods.berkeley.edu/notebooks/Index.html

# Chapter 3: Functions

https://pythonnumericalmethods.berkeley.edu/notebooks/chapter03.06-Summary-and-Problems.html#problems

Only those problems that need to be solved in a notebook environment

1. Recall that the hyperbolic sine, denoted by sinh, is $\frac{exp(x) - exp(-x)}{2}$. Write a function __my_sinh(x)__, where the output __y__ is the hyperbolic sine computed on __x__. Assume that __x__ is a 1 by 1 float. 

In [ ]:
import math

def my_sinh(x):

  return (math.exp(x) - math.exp(-x))/2

Test cases.

In [ ]:
print(my_sinh(0))
print(my_sinh(1))
print(my_sinh(2))

0.0
1.1752011936438014
3.626860407847019


2. Write a function my_checker_boars(n), where the output m is an nxn array with the following form:

<pre>

        1 0 1 0 1
        0 1 0 1 0
 m =    1 0 1 0 1
        0 1 0 1 0
        1 0 1 0 1

</pre>

Note that the upper-left element should always be 1. Assume that n is a strictly positive integer.

In [ ]:
import numpy as np

def my_checker_boards(n):
  arr = np.zeros((n,n), dtype = int)

  for idx in range(0,n):
    arr[idx,idx] = 1 # all diagonal elements must be 1

    # if row number is odd i.e. 1,3,5 we modify all odd column values to 1. However,
    # python is zero-indexed and thus 1,3,5 are represented by 0,2,4.
    # if row number is even then we modify odd values and if its odd then we modify even values
    if (idx+1) % 2 == 1:
      arr[idx,[val for val in range(n) if val % 2 == 0]] = 1

    else:
      arr[idx,[val for val in range(n) if val % 2 == 1]] = 1

  # n is 1 then we get a 1 by 1 array, which is nothing but a scalar so we return the scalar
  if n == 1:
    arr = arr[0,0]
  return arr

Test cases

In [ ]:
print(my_checker_boards(1))
print()

print(my_checker_boards(2))
print()

print(my_checker_boards(3))
print()

print(my_checker_boards(5))

1

[[1 0]
 [0 1]]

[[1 0 1]
 [0 1 0]
 [1 0 1]]

[[1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]]


Additional cases to verify 4 and 7

In [ ]:
print(my_checker_boards(4))
print()

print(my_checker_boards(7))

[[1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]]

[[1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]]


3. Write a function my_triangle(b,h) where the output is the area of a triangle with base, b, and height, h. Recall that the area of a triangle is one-half the base times the height. Assume that b and h are just 1 by 1 float numbers.

In [ ]:
def my_triangle(b,h):

  return (1/2) * b * h

Test cases

In [ ]:
print(my_triangle(1, 1))

print(my_triangle(2, 1))
   
print(my_triangle(12, 5))

0.5
1.0
30.0


4. Write a function my_split_matrix(m), where m is an array, the output is a list [m1, m2] where m1 is the left half of m, and m2 is the right half of m. In the case where there is an odd number of columns, the middle column should go to m1. Assume that m has at least two columns.

In [ ]:
def my_split_matrix(m):

  m1_dims = math.ceil(m.shape[1]/2)
  m2_dims = math.floor(m.shape[1]/2)

  m1 = m[:,:m1_dims]
  m2 = m[:,-m2_dims:]

  return m1, m2

Test cases

In [ ]:
m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  
m1, m2 = my_split_matrix(m)  

print(m)
print()
print(m1)
print()
print(m2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2]
 [4 5]
 [7 8]]

[[3]
 [6]
 [9]]


In [ ]:
m = np.ones((5, 5))
m1, m2 = my_split_matrix(m)  

print(m)
print()
print(m1)
print()
print(m2)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


4. Write a function my_cylinder(r,h), where r and h are the radius and height of a cylinder, respectively, and the output is a list [s, v] where s and v are the surface area and volume of the same cylinder, respectively. Recall that the surface area of a cylinder is $2\pi r^2 + 2\pi rh$, and the volume is $\pi r^2h$. Assume that r and h are 1 by 1 float.

In [ ]:
def my_cylinder(r, h):

  surface_area = 2*math.pi*(r**2) + 2*math.pi*r*h
  volume = math.pi*(r**2)*h

  return [surface_area, volume]

Test cases

In [ ]:
print(my_cylinder(1,5))
print()
print(my_cylinder(2,4))

[37.69911184307752, 15.707963267948966]

[75.39822368615503, 50.26548245743669]


6. Write a function my_n_odds(a), where a is a one-dimensional array of floats and the output is the number of odd numbers in a.

In [ ]:
def my_n_odds(a):

  return sum(a % 2 == 1)

Test cases

In [ ]:
print(my_n_odds(np.arange(100)))
print()
print(my_n_odds(np.arange(2, 100, 2)))

50

0


7. Write a function my_twos(m,n), where the output is an mxn array of twos. Assume that m and n are strictly positive integers.

In [ ]:
def my_twos(m,n):
  return np.ones((m,n)) * 2

Test cases

In [ ]:
print(my_twos(3, 2))
print()
print(my_twos(1, 4))

[[2. 2.]
 [2. 2.]
 [2. 2.]]

[[2. 2. 2. 2.]]


8. Write a lambda function that takes in x and y, and output the value of x - y.

In [ ]:
lambda x,y: x - y

<function __main__.<lambda>(x, y)>

9. Write a function add_string(s1,s2), where the output is the concatenation of the strings s1 and s2.

In [ ]:
def add_string(s1, s2):
  return s1 + s2

Test cases

In [ ]:
s1 = add_string('Programming', ' ')
s2 = add_string('is ', 'fun!')

add_string(s1, s2)

'Programming is fun!'

10. Generate the following errors:

- TypeError: fun() missing 1 required positional argument: 'a'

- IndentationError: expected an indented block

In [ ]:
# type error
my_n_odds()

TypeError: ignored

In [ ]:
# indentation error
def func():
return 1

IndentationError: ignored

11. Write a function greeting(name,age), where name is a string, age is a float, and the output is a string 'Hi, my name is XXX and I am XXX years old.' where XXX are the input name and age, respectively.

In [ ]:
def greeting(name, age):
  return f"Hi, my name is {name} and I am {age} years old."

Test cases

In [ ]:
greeting('John', 26)

'Hi, my name is John and I am 26 years old.'

In [ ]:
greeting('Kate', 19)

'Hi, my name is Kate and I am 19 years old.'

12. Let r1 and r2 be the radius of circles with the same center and let r2>r1. Write a function my_donut_area(r1, r2), where the output is the area outside of the circle with radius r1 and inside the circle with radius r2. Make sure that the function is vectorized. Assume that r1 and r2 are one-dimensional array of the same size.

Circles with same center means concentric circles. The region between two concentric circles of different radii is called an annulus. (https://mathworld.wolfram.com/ConcentricCircles.html#:~:text=Concentric%20circles%20are%20circles%20with,radii%20is%20called%20an%20annulus.)

In [ ]:
# annulus would be the difference between the area of the larger circle and the area of the smaller circle.
def my_donut_area(r1, r2):
  return np.pi*(r2**2) - np.pi*(r1**2)

Test cases

In [ ]:
my_donut_area(np.arange(1, 4), np.arange(2, 7, 2))

array([ 9.42477796, 37.69911184, 84.82300165])

13. Write a function my_within_tolerance(A,a,tol), where the output is an array or list of the indices in A such that |A−a| < tol. Assume that A is a one-dimensional float list or array and that a and tol are 1 by 1 floats.

In [ ]:
def my_within_tolerance(A, a, tol):
  A = np.array(A)
  return list(np.where(np.abs(A - a) < tol)[0])

Test cases

In [ ]:
my_within_tolerance([0, 1, 2, 3], 1.5, 0.75)

[1, 2]

In [ ]:
my_within_tolerance(np.arange(0, 1.01, 0.01), 0.5, 0.03)

[47, 48, 49, 50, 51, 52]

14. Write a function bounding_array(A,top,bottom), where the output is equal to the array A wherever bottom < A < top, the output is equal to bottom wherever A <= bottom, and the output is equal to top wherever A >= top. Assume that A is one-dimensional float array and that top and bottom are 1 by 1 floats.

In [ ]:
def bounding_array(A,top,bottom):

  return np.where(A >= top, top, np.where(A <= bottom, bottom, A) )

Test cases

In [ ]:
bounding_array(np.arange(-5, 6, 1), 3, -3)

array([-3, -3, -3, -2, -1,  0,  1,  2,  3,  3,  3])