These are the exercise problems from the book Python programming and Numerical methods book:

https://pythonnumericalmethods.berkeley.edu/notebooks/Index.html

# Chapter 11: Reading and Writing Data

https://pythonnumericalmethods.berkeley.edu/notebooks/chapter11.06-Summary-and-Problems.html

Only those problems that need to be solved in a notebook environment

In [1]:
from google.colab import drive
drive.mount('gdrive')

Mounted at gdrive


In [2]:
cd gdrive/My Drive/Python practice/Python programming and Numerical methods

/content/gdrive/My Drive/Python practice/Python programming and Numerical methods


In [3]:
!ls

Complexity.ipynb   exercise_2.ipynb  exercise_6.ipynb  lst1.txt
Debugging.ipynb    exercise_3.ipynb  exercise_7.ipynb  Salary_Data.csv
exercise_11.ipynb  exercise_4.ipynb  exercise_8.ipynb
exercise_1.ipynb   exercise_5.ipynb  exercise_9.ipynb


1. Create a list and save it in a text file that each of the item in the list will take one line.

In [4]:
lst = ['I am fine.\n','I will return home tomorrow.\n','See you then.\n']

# first using writelines
file1 = open('lst1.txt', 'w')
file1.writelines(lst)
file1.close()

In [5]:
# reading the file
lst_read = open('lst1.txt', 'r')
lst_read.readlines()

['I am fine.\n', 'I will return home tomorrow.\n', 'See you then.\n']

writelines requires a separator like \n after each element and only then it stores them one line at a time. But what if the separator was not provided. This is where we write lines one at a time



In [9]:
# writing one element at a time
lst1 = ['I am fine.','I will return home tomorrow.','See you then.']

with open('lst2.txt', 'w') as f:
  for element in lst1:
    f.write(f"{element} \n")

In [10]:
# reading the file
lst_read = open('lst2.txt', 'r')
lst_read.readlines()

['I am fine. \n', 'I will return home tomorrow. \n', 'See you then. \n']

---

2. Save the same list in problem 1 to a CSV file.

In [17]:
import pandas as pd

pd.DataFrame(lst1).to_csv('lst1.csv', index = False)

In [18]:
# loading the file
pd.read_csv('lst1.csv')

0
0                    I am fine.
1  I will return home tomorrow.
2                 See you then.

---

3. Create a 2D numpy array, and save it to CSV file and read it back to a 2D array.

In [19]:
import numpy as np

rand_mat = np.random.random((10,5))
rand_mat

array([[0.48042323, 0.00360611, 0.42158686, 0.99201286, 0.56607363],
       [0.82252425, 0.69449276, 0.87974751, 0.49738096, 0.12114612],
       [0.16501351, 0.83827627, 0.87911738, 0.34289859, 0.95583979],
       [0.52101057, 0.86387205, 0.57449079, 0.53902586, 0.81277601],
       [0.88368194, 0.28982131, 0.46917712, 0.4101232 , 0.51358602],
       [0.96456011, 0.66662309, 0.03069778, 0.61739563, 0.77367028],
       [0.29510422, 0.70848473, 0.13540602, 0.28487   , 0.48885038],
       [0.73342718, 0.2473953 , 0.98560109, 0.30542319, 0.08569662],
       [0.60068003, 0.68120704, 0.40702874, 0.6122194 , 0.19338678],
       [0.878192  , 0.80998708, 0.85066035, 0.20369538, 0.21899771]])

In [22]:
# saving with 6 decimal points
np.savetxt('rand_mat.csv', rand_mat, fmt = '%.6f')

In [23]:
# loading the saved file
np.loadtxt('rand_mat.csv')

array([[0.480423, 0.003606, 0.421587, 0.992013, 0.566074],
       [0.822524, 0.694493, 0.879748, 0.497381, 0.121146],
       [0.165014, 0.838276, 0.879117, 0.342899, 0.95584 ],
       [0.521011, 0.863872, 0.574491, 0.539026, 0.812776],
       [0.883682, 0.289821, 0.469177, 0.410123, 0.513586],
       [0.96456 , 0.666623, 0.030698, 0.617396, 0.77367 ],
       [0.295104, 0.708485, 0.135406, 0.28487 , 0.48885 ],
       [0.733427, 0.247395, 0.985601, 0.305423, 0.085697],
       [0.60068 , 0.681207, 0.407029, 0.612219, 0.193387],
       [0.878192, 0.809987, 0.85066 , 0.203695, 0.218998]])

---

4. Save the same array in problem 3 to a pickle file and load it back.

In [24]:
import pickle

pickle.dump(rand_mat, open('rand_mat.pkl', 'wb'))

In [27]:
pickle.load(open('rand_mat.pkl', 'rb'))

array([[0.48042323, 0.00360611, 0.42158686, 0.99201286, 0.56607363],
       [0.82252425, 0.69449276, 0.87974751, 0.49738096, 0.12114612],
       [0.16501351, 0.83827627, 0.87911738, 0.34289859, 0.95583979],
       [0.52101057, 0.86387205, 0.57449079, 0.53902586, 0.81277601],
       [0.88368194, 0.28982131, 0.46917712, 0.4101232 , 0.51358602],
       [0.96456011, 0.66662309, 0.03069778, 0.61739563, 0.77367028],
       [0.29510422, 0.70848473, 0.13540602, 0.28487   , 0.48885038],
       [0.73342718, 0.2473953 , 0.98560109, 0.30542319, 0.08569662],
       [0.60068003, 0.68120704, 0.40702874, 0.6122194 , 0.19338678],
       [0.878192  , 0.80998708, 0.85066035, 0.20369538, 0.21899771]])

---

5. Create a dictionary and save it to a JSON file.

In [28]:
dict_a = {'a': 1, 'b': 2, 'c': 3, 'd': 4}

import json

json.dump(dict_a, open('my_dict.json', 'w'))

In [29]:
json.load(open('my_dict.json', 'r'))

{'a': 1, 'b': 2, 'c': 3, 'd': 4}

---

6. Create a 1D numpy array, and save it to a JSON file with the key named ‘data’. Then load it back.

numpy array cannot be directly stored as json object as it is deserializable. We need to first convert it to list and store it and then load it as a dictionary and convert to numpy array.

This is one big benefit of pickle over json as we saw earlier, pickle could directly store numpy array.

In [30]:
data = np.array([1,2,3,4,5])
data

array([1, 2, 3, 4, 5])

In [33]:
{'data': data.tolist()}

{'data': [1, 2, 3, 4, 5]}

In [34]:
json.dump({'data': data.tolist()}, open('data.json', 'w'))

In [38]:
np.array(json.load(open('data.json', 'r'))['data'])

array([1, 2, 3, 4, 5])