These are the exercise problems from the book Python programming and Numerical methods book:

https://pythonnumericalmethods.berkeley.edu/notebooks/Index.html

# Chapter 6: Recursion

https://pythonnumericalmethods.berkeley.edu/notebooks/chapter06.03-Summary-and-Problems.html#problems

Only those problems that need to be solved in a notebook environment

1. Write a function my_sum(lst) where lst is a list, and the output is the sum of all the elements of lst. You can use recursion or iteration to solve the problem, but do not use Python’s function sum.

Iteration

In [1]:
def my_sum(lst):

  sum_val = 0

  for num in lst:
    sum_val += num

  return sum_val

In [2]:
# Output: 6
my_sum([1, 2, 3])

6

In [3]:
# Output: 5050
my_sum(range(1,101))

5050

Recursion

In [4]:
def my_sum(lst):

  # base case: just return the first value as is if list contains only one element
  if len(lst) == 1:
    return lst[0]

  # else take the first element and add it by the sum of all other elements
  else:
    return lst[0] + my_sum(lst[1:])

Recursion breakdown of the function:

input: [1,2,3]

Here, it will look at the list [1,2,3] and since its length is not 1, it will go into the else block.

__solution will be:__ <br>
__s1 = lst[0] + my_sum([lst[1:]])= 1 + my_sum([2,3])__ 

now it will wait till it has the solution to my_sum([2,3]).

it will again check the if condition and since its length is not 1, it will again get into the else block.

__solution will be:__ <br>
__s2 = lst[0] + my_sum([lst[1:]]) = 2 + my_sum([3])__

now it will wait for result of my_sum([3])

here length of the list [3] is 1 and thus it returns 3.

so now it will go and replace that value in s2.

__s2 = 2 + 3 = 5__

Finally, it will substitute 5 in s1.

__s1 = 1 + 5 = 6__

In [5]:
# Output: 6
my_sum([1, 2, 3])

6

In [6]:
# Output: 5050
my_sum(range(1,101))

5050

2. Chebyshev polynomials are defined recursively. Chebyshev polynomials are separated into two kinds: first and second. Chebyshev polynomials of the first kind, 𝑇𝑛(𝑥), and of the second kind, 𝑈𝑛(𝑥), are defined by the following recurrence relations:

$$T_n(x) = \left\{
\begin{array}{ll}
      1 & if & n = 0 \\
      x & if & n = 1 \\
      2xT_{n-1}(x) - T_{n-2}(x) &  & otherwise
\end{array}
\right.    $$ 

$$U_n(x) = \left\{
\begin{array}{ll}
      1 & if & n = 0 \\
      2x & if & n = 1 \\
      2xU_{n-1}(x) - U_{n-2}(x) &  & otherwise
\end{array}
\right.    $$ 

<br><br>

Write a function my_chebyshev_poly1(n,x), where the output y is the n-th Chebyshev polynomial of the first kind evaluated at x. Be sure your function can take list inputs for x. You may assume that x is a list. The output variable, y, must be a list also.

In [7]:
def my_chebyshev_poly1(n,x):

  # first base case: return a list of ones of the same size as x if n == 0
  if n == 0:
    return [1]*len(x)

  # second base case: return x as is if n == 1
  elif n == 1:
    return x

  # recursive case: return solutions using the formula provided above
  else:
    return [2*x[idx]*my_chebyshev_poly1(n-1,x)[idx] - my_chebyshev_poly1(n-2,x)[idx] for idx in range(len(x))]

In [8]:
x = [1, 2, 3, 4, 5]

In [9]:
# Output: [1, 1, 1, 1, 1]
my_chebyshev_poly1(0,x)

[1, 1, 1, 1, 1]

In [10]:
# Output: [1, 2, 3, 4, 5]
my_chebyshev_poly1(1,x)

[1, 2, 3, 4, 5]

In [11]:
# Output: [1, 26, 99, 244, 485]
my_chebyshev_poly1(3,x)

[1, 26, 99, 244, 485]

Constructing the logic:

input: (3, [1,2,3,4,5])

it checks if n == 0 and its not and thus it moves to check if n == 1 and its also false.

now it computes: <br>
[2 * x[idx] * my_chebyshev_poly1(n-1,x)[idx] - my_chebyshev_poly1(n-2,x)[idx] for idx in range(len(x))]

where x is a list, outputs of both my_chebyshev_poly1(n-1,x) and my_chebyshev_poly1(n-2,x) are lists. It aims to perform an element by element multiplication and subtraction. 

So, our first sub problem is dependent on my_chebyshev_poly1(n-1,x) and my_chebyshev_poly1(n-2,x)

let the first sub problem be s1

s1 = [2 * x[idx] * my_chebyshev_poly1(2,x)[idx] - my_chebyshev_poly1(1,x)[idx] for idx in range(len(x))]

here for my_chebyshev_poly1(1,x), n == 1 and thus output is: <br>
my_chebyshev_poly1(1,x) = x = [1,2,3,4,5]

now we wait for solution of my_chebyshev_poly1(2,x)

my_chebyshev_poly1(2,x) = [2 * x[idx] * my_chebyshev_poly1(1,x)[idx] - my_chebyshev_poly1(0,x)[idx] for idx in range(len(x))]

here for my_chebyshev_poly1(0,x), n == 0 and output is: <br>
my_chebyshev_poly1(0,x) = [1,1,1,1,1]

now for my_chebyshev_poly1(2,x) we get:

[2 * 1 * 1 - 1, 2 * 2 * 2 - 1, 2 * 3 * 3 - 1, 2 * 4 * 4 - 1, 2 * 5 * 5 - 1]

= [1, 7, 17, 31, 49]

replacing my_chebyshev_poly1(2,x) in s1:

s1 = [2 * 1 * 1 - 1, 2 * 2 * 7 - 2, 2 * 3 * 17 - 3, 2 * 4 * 31 - 4, 2 * 5 * 49 - 5]

= [1, 26, 99, 244, 485]

3. The Ackermann function, A, is a quickly growing function that is defined by the recursive relationship:


$$A(m,n) = \left\{
\begin{array}{ll}
      n+1 & if & m = 0 \\
      A(m-1,1) & if & m > 0 \text{ and } n = 1 \\
      A(m-1, A(m,n-1)) & if & m > 0 \text{ and } n > 0
\end{array}
\right.    $$

<br> <br>

Write a function my_ackermann(m,n), where the output is the Ackermann function compuated for m and n.

my_ackermann(4,4) is so large that it would be difficult to write down. Although the Ackermann function does not have many practical uses, the inverse Ackermann function has several uses in robotic motion planning.

__note:__ There is a mistake in the question. The first recursive case should be A(m-1, 1) if m > 0 and n == 0.

https://mathworld.wolfram.com/AckermannFunction.html

https://rosettacode.org/wiki/Ackermann_function#:~:text=The%20Ackermann%20function%20is%20usually,%3E%200%20and%20n%20%3E%200.&text=Its%20arguments%20are%20never%20negative%20and%20it%20always%20terminates.&text=.,-Arbitrary%20precision%20is

In [12]:
def my_ackermann(m,n):

  # base case: if m == 0 then return n+1
  if m == 0:
    return n + 1
  
  # first recursive case 
  elif m > 0 and n == 0:
    return my_ackermann(m-1, 1)

  # second recursive case
  elif m > 0 and n > 0:
    return my_ackermann(m-1, my_ackermann(m, n-1))

In [13]:
# Output: 3
my_ackermann(1,1)

3

In [14]:
# Output: 4
my_ackermann(1,2)

4

In [15]:
# Output: 9
my_ackermann(2,3)

9

In [16]:
# Output: 61
my_ackermann(3,3)

61

In [17]:
# Output: 125
my_ackermann(3,4)

125

__Breaking down the recursion:__

input: (1,1)

m = 1, n = 1

__first run:__

m is not equal to 0 so it moves to the next condition

m is greater than 0 but n is not equal to 0 and thus it moves to the next condition

soln = my_ackermann(0, my_ackermann(1, 0)) 

now it will wait the solutions of first my_ackermann(1, 0) and then my_ackermann(0, my_ackermann(1, 0)).

<br>

__second run:__

For my_ackermann(1, 0),

m = 1, n = 0

m is not equal to 0 so it moves to the next condition

m is greater than 0 and n is equal to 0 

my_ackermann(1, 0) = my_ackermann(0, 1)

<br>

__third run:__

For my_ackermann(0, 1),

m = 0, n = 1

m == 0

my_ackermann(0, 1) = n + 1 = 1 + 1 = 2

__Now, we got to the base case and we start substituing values.__

my_ackermann(1, 0) = my_ackermann(0, 1) = 2

soln = my_ackermann(0, my_ackermann(1, 0)) = my_ackermann(0, 2)

<br>

__fourth run:__

now for my_ackermann(0, 2) 

m = 0, n = 2

my_ackermann(0, 2) = n + 1 = 2 + 1 = 3

__Thus, soln = 3__


4. A function, C(n,k), which computes the number of different ways of uniquely choosing k objects from n without repetition, is commonly used in many statistics applications. For example, how many three-flavored ice cream sundaes are there if there are 10 icecream flavors? To solve this problem we would have to compute C(10,3), the number of ways of choosing three unique icecream flavors from 10. The function C is commonly called “n choose k.” You may assume that n and k are integers.

If n = k, then clearly C(n,k) = 1 because there is only way to choose n objects from n objects.

If k = 1, then C(n,k) = n because choosing each of the n objects is a way of choosing one object from n. For all other cases, C(n,k) = C(n-1,k) + C(n-1,k-1). Can you see why?

Write a function my_n_choose_k(n,k) that computes the number of times 𝑘
 objects can be uniquely chosen from 𝑛
 objects without repetition.

In [18]:
def my_n_choose_k(n,k):
    
    # first base case
    if n == k:
      return 1

    # second base case
    elif k == 1:
      return n
    
    else:
      return my_n_choose_k(n-1, k) + my_n_choose_k(n-1, k-1)

In [19]:
# Output: 10
my_n_choose_k(10,1)

10

In [20]:
# Output: 1
my_n_choose_k(10,10)

1

In [21]:
# Output: 120
my_n_choose_k(10,3)

120

In [22]:
# simple case 3C2 = 3
my_n_choose_k(3,2)

3

__Explaing the recursion:__

input: n = 3, k = 2

n $\neq$ k

k $\neq$ 1

__soln = my_n_choose_k(n - 1, k) + my_n_choose_k(n-1, k-1) = my_n_choose_k(3 - 1, 2) + my_n_choose_k(3-1, 2-1) = my_n_choose_k(2, 2) + my_n_choose_k(2, 1)__

__For my_n_choose_k(2, 2)__

input: n = 2, k = 2

n = k and thus it returns 1

my_n_choose_k(2, 2) = 1

__For my_n_choose_k(2, 1)__

input: n = 2, k = 1

n $\neq$ k

k = 1 and thus it returns n = 2

my_n_choose_k(2, 1) = 2

__soln: 1 + 2 = 3__



__Explanation for why in all other cases C(n,k) = C(n-1,k) + C(n-1,k-1)__

https://math.stackexchange.com/questions/780627/show-that-cn-k-cn-1-k-cn-1-k-1

5. For any purchases paid in cash, the seller must return money that was overpaid. This is commonly referred to as "giving change." The bills and coins required to properly give change can be defined by a recursive relationship. If the amount paid is more than \$100 more than the cost,then a \$100 bill is returned, which is the result of a recursive call to the change function with \$100 subtracted from the amount paid. If the amount paid is more than \$50 over the cost of the item, then a \$50 bill is returned, along with the result of a recursive call to the change function with \$50 subtracted. Similar clauses can be given for every denomination of US currency. The denominations of US currency, in dollars, are 100, 50, 20, 10, 5, 1, 0.25, 0.10, 0.05, and 0.01. For this problem we will ignore the 2-dollar bill, which is not in common circulation. Assume that __cost__ and __paid__ are scalars, and that paid >= cost. The output variable, __change__, must be a list as shown in the test case.

Use recursion to program a function my_change(cost, paid) where cost is the cost of the item, paid is the amount paid, and the output change is a list of bills and coins that should be returned to the seller. Note: Watch out for the base case! 

In [23]:
# using change as variable output

def my_change(cost, paid):

  change = []

  # base case 1
  if paid == cost:
    change = []

  # base case 2. We round it to 2 as it should check if its exactly 0.01 as 0.09999 != 0.01
  elif round(paid - cost, 2) == 0.01:
    change = [0.01]

  # recursive case 1
  elif paid - cost > 100:
    change = [100] + my_change(cost, paid-100)

  # recursive case 2
  elif paid - cost > 50:
    change = [50] + my_change(cost, paid-50)

  # recursive case 3
  elif paid - cost > 20:
    change = [20] + my_change(cost, paid-20)

  # recursive case 4
  elif paid - cost > 10:
    change = [10] + my_change(cost, paid-10)

  # recursive case 5
  elif paid - cost > 5:
    change = [5] + my_change(cost, paid-5)

  # recursive case 6
  elif paid - cost > 1:
    change =  [1] + my_change(cost, paid-1)

  # recursive case 7
  elif paid - cost > 0.25:
    change = [0.25] + my_change(cost, paid-0.25)

  # recursive case 8
  elif paid - cost > 0.1:
    change = [0.1] + my_change(cost, paid-0.1)

  # recursive case 9
  elif paid - cost > 0.05:
    change = [0.05] + my_change(cost, paid-0.05)

  # recursive case 10
  elif paid - cost > 0.01:
    change = [0.01] + my_change(cost, paid-0.01)

  return change

In [24]:
# using return statements after each condition

def my_change1(cost, paid):

  if paid == cost:
    return []

  elif round(paid - cost, 2) == 0.01:
    return [0.01] 

  elif paid - cost > 100:
    return [100] + my_change(cost, paid-100)

  elif paid - cost > 50:
    return [50] + my_change(cost, paid-50)

  elif paid - cost > 20:
    return [20] + my_change(cost, paid-20)

  elif paid - cost > 10:
    return [10] + my_change(cost, paid-10)

  elif paid - cost > 5:
    return [5] + my_change(cost, paid-5)

  elif paid - cost > 1:
    return [1] + my_change(cost, paid-1)

  elif paid - cost > 0.25:
    return [0.25] + my_change(cost, paid-0.25)

  elif paid - cost > 0.1:
    return [0.1] + my_change(cost, paid-0.1)

  elif paid - cost > 0.05:
    return [0.05] + my_change(cost, paid-0.05)

  elif paid - cost > 0.01:
    return [0.01] + my_change(cost, paid-0.01)


In [25]:
# Output: [50.0, 20.0, 1.0, 1.0, 0.25, 0.10, 0.05, 0.01, 0.01, 0.01]
my_change(27.57, 100)

[50, 20, 1, 1, 0.25, 0.1, 0.05, 0.01, 0.01, 0.01]

In [26]:
# Output: [50.0, 20.0, 1.0, 1.0, 0.25, 0.10, 0.05, 0.01, 0.01, 0.01]
my_change1(27.57, 100)

[50, 20, 1, 1, 0.25, 0.1, 0.05, 0.01, 0.01, 0.01]

In [27]:
sum(my_change(27.57, 100))

72.43

In [28]:
72.43 + 27.57

100.0

__Exploring the steps:__

input = (27,57, 100)

__breaking into subproblems:__

soln = [50] + my_change(27.57, 50)  

my_change(27.57, 50) = [20] + my_change(27.57, 30) 

my_change(27.57, 30) = [1] + my_change(27.57, 29)

my_change(27.57, 29) = [1] + my_change(27.57, 28)

my_change(27.57, 28) = [0.25] + my_change(27.57, 27.75)

my_change(27.57, 27.75) = [0.1] + my_change(27.57, 27.65)

my_change(27.57, 27.65) = [0.05] + my_change(27.57, 27.60)

my_change(27.57, 27.60) = [0.01] + my_change(27.57, 27.59)

my_change(27.57, 27.59) = [0.01] + my_change(27.57, 27.58)

my_change(27.57, 27.58) = [0.01] + my_change(27.57, 27.57)

my_change(27.57, 27.57) = []


-----------------------------------------------------------------------

__after base case combining the solutions:__

my_change(27.57, 27.58) = [0.01] + [] = [0.01]

my_change(27.57, 27.59) = [0.01] + [0.01] = [0.01, 0.01]

my_change(27.57, 27.60) = [0.01] + [0.01, 0.01] = [0.01, 0.01, 0.01]

my_change(27.57, 27.65) = [0.05] + [0.01, 0.01, 0.01] = [0.05, 0.01, 0.01, 0.01]

my_change(27.57, 27.75) = [0.1] + [0.05, 0.01, 0.01, 0.01] = [0.1, 0.05, 0.01, 0.01, 0.01]

my_change(27.57, 28) = [0.25] + [0.1, 0.05, 0.01, 0.01, 0.01] = [0.25, 0.1, 0.05, 0.01, 0.01, 0.01]

my_change(27.57, 29) = [1] + [0.25, 0.1, 0.05, 0.01, 0.01, 0.01] = [1, 0.25, 0.1, 0.05, 0.01, 0.01, 0.01]

my_change(27.57, 30) = [1] + [1, 0.25, 0.1, 0.05, 0.01, 0.01, 0.01] = [1, 1, 0.25, 0.1, 0.05, 0.01, 0.01, 0.01]

my_change(27.57, 50) = [20] + [1, 1, 0.25, 0.1, 0.05, 0.01, 0.01, 0.01] = [20, 1, 1, 0.25, 0.1, 0.05, 0.01, 0.01, 0.01]

__soln = [50] + [20, 1, 1, 0.25, 0.1, 0.05, 0.01, 0.01, 0.01] = [50, 20, 1, 1, 0.25, 0.1, 0.05, 0.01, 0.01, 0.01]__

6. The golden ratio Φ, is the limit of $\frac{F(n+1)}{F(n)}$ as n goes to infinity and F(n) is the n-th Fibonacci number, which can be shown to be exactly $\frac{1+\sqrt{5}}{2}$ and is approximately 1.62. We say that G(n) = $\frac{F(n+1)}{F(n)}$ is the nth approximation of the golden ratio, and G(1) = 1.

It can also be shown that Φ is also the limit of the continued fraction:

Φ = $1 + \frac{1}{1 + \frac{1}{1 + \frac{1}{1 + \frac{1}{...}}}}$

Write a recursive function with header my_golden_ratio(n), where the output is the n-th approximation of the golden ratio according to the continued fraction recursive relationship. You should use the continued fraction approximation for the Golden ratio, not the 𝐺(𝑛)=𝐹(𝑛+1)/𝐹(𝑛)
definition. However for both definitions, 𝐺(1)=1.

Studies have shown that rectangles with aspect ratio (i.e., length divided by width) close to the golden ratio are more pleasing than rectangles that do not. What is the aspect ratio of many wide-screen TV’s and movie screens?

In [29]:
def my_golden_ratio(n):

  # base case
  if n == 1:
    return 1

  # recursive case
  else:
    # return 1 + 1/(1 + 1/(my_golden_ratio(n-1)) ) # this gives a much more closer approximation as it performs one more operation of 1 + 1/(1 + ...)
    return 1 + 1/(my_golden_ratio(n-1))

In [30]:
# Output: 1.618181818181818
my_golden_ratio(10)

1.6181818181818182

In [31]:
import numpy as np
(1 + np.sqrt(5))/2

1.618033988749895

7. The greatest common divisor of two integers a and b is the largest integer that divides both numbers without remainder, and the function to compute it is denoted by gcd(a,b). The gcd function can be written recursively. If b equals 0, then a is the greatest common divisor. Otherwise, gcd(a,b) = gcd(b,a%b) where a%b is the remainder of a divided by b. Assume that a and b are integers.

Write a recursive function my_gcd(a,b) that computes the greatest common divisor of a and b. Assume that a and b are integers.

In [32]:
def my_gcd(a,b):

  # base case
  if b == 0:
    return a

  # recursive case
  else:
    return my_gcd(b, a % b)

In [33]:
# Output: 2
my_gcd(10, 4)

2

In [34]:
# Output: 11
my_gcd(33, 121)

11

In [35]:
# Output: 1
my_gcd(18, 1)

1

__Explaining the recursion:__

input: a = 10, b = 4

b != 0

soln = my_gcd(4, 10 % 4) = my_gcd(4, 2)

my_gcd(4, 2) = my_gcd(2, 4 % 2) = my_gcd(2, 0)

my_gcd(2, 0) = 2 (since b = 0 we return a)

__Thus, soln = 2__

--------------------------------------------------------------------

__Example 2:__

input: a = 33, b = 121

b != 0

soln = my_gcd(121, 121 % 33) = my_gcd(121, 22)

my_gcd(121, 22) = my_gcd(22, 121 % 22) = my_gcd(22, 11)

my_gcd(22, 11) = my_gcd(11, 22 % 11) = my_gcd(11, 0)

my_gcd(11,0) = 11

__Thus, soln = 11__




8. Pascal's triangle is an arrangement of numbers such that each row is equivalent to the coefficients of the binomial expansion of $(𝑥+𝑦)^{(𝑝−1)}$, where p is some positive integer more than or equal to 1. For example, $(𝑥+𝑦)^2 = 1𝑥^2 + 2𝑥𝑦 + 1𝑦^2$ so the third row of Pascal's triangle is 1 2 1.

Let $𝑅_𝑚$ represent the m-th row of Pascal's triangle, and $𝑅_𝑚(𝑛)$ be the 𝑛-th element of the row. By definition, $𝑅_𝑚$ has m elements, and $𝑅_𝑚(1) = 𝑅_𝑚(𝑛) = 1$. The remaining elements are computed by the following recursive relationship: $𝑅_𝑚(𝑖) = 𝑅_{𝑚−1}(𝑖−1)+𝑅_{𝑚−1}(𝑖)$ for 𝑖=2,…,𝑚−1. The first few rows of Pascal’s triangle are depicted in the following figure. You may assume that m is a strictly positive integer. The output variable, row, must be a list.

<pre>

              1
            1   1
          1   2   1
        1   3   3   1
      1   4   6   4   1
    1   5  10   10  5   1

</pre>

Write a function with my_pascal_row(m) where output variable row is the m-th row of the Pascal triangle. You may assume that m is a strictly positive integer.

In [36]:
list(range(1,3))

[1, 2]

In [37]:
def my_pascal_row(m):

  # base case
  if m == 1:
    return [1]
  
  # base case 2
  if m == 2:
    return [1, 1]

  # recursive case
  else:
    return [1] + [my_pascal_row(m-1)[i-1] + my_pascal_row(m-1)[i] for i in range(1,m-1)] + [1]

In [38]:
# Output: [1]
my_pascal_row(1)

[1]

In [39]:
# Output: [1, 1]
my_pascal_row(2)

[1, 1]

In [40]:
# Output: [1, 2, 1]
my_pascal_row(3)

[1, 2, 1]

In [41]:
# Output: [1, 3, 3, 1]
my_pascal_row(4)

[1, 3, 3, 1]

In [42]:
# Output: [1, 4, 6, 4, 1]
my_pascal_row(5)

[1, 4, 6, 4, 1]

In [43]:
# Output: [1, 5, 10, 10, 5, 1]
my_pascal_row(6)

[1, 5, 10, 10, 5, 1]

explaining the recursion:

input: 3

m != 1

m != 2

soln = [1] + [my_pascal_row(2)[i-1] + my_pascal_row(2)[i] for i in range(1,2)] + [1]

my_pascal_row(2) = [1,1]

i - 1 = 1 - 1 = 0 <br>
i = 1

soln = [1] + [[1,1][0] + [1,1][1]] + [1]

soln = [1] + [1 + 1] + [1] = [1,2,1]


-----------------------------------------------------------------------

__example 2:__

input: 4

m != 1

m != 2

soln = [1] + [my_pascal_row(3)[i-1] + my_pascal_row(3)[i] for i in range(1,3)] + [1]

my_pascal_row(3) = [1] + [my_pascal_row(2)[i-1] + my_pascal_row(2)[i] for i in range(1,2)] + [1]

my_pascal_row(3) = [1,2,1]

[my_pascal_row(3)[i-1] + my_pascal_row(3)[i] for i in range(1,3)] = 
[[1,2,1][0] + [1,2,1][1], [1,2,1][1] + [1,2,1][2]] = [1 + 2, 2 + 1] = [3,3]

soln = [1] + [3,3] + [1] = [1,3,3,1]

9. Consider a 𝑛×𝑛 matrix of the following form:


$$A = \begin{bmatrix}1 & 1 & 1 & 1 & 1\\1 & 0 & 0 & 0 & 0\\1 & 0 & 1 & 1 & 0\\1 & 0 & 0 & 1 & 0\\1 & 1 & 1 & 1 & 0\end{bmatrix}$$

where the ones form a right spiral. Write a function my_spiral_ones(n) that produces an 𝑛×𝑛 matrix of the given form. Take care that the recursive steps are in the correct order (i.e., the ones go right, then down, then left, then up, then right, etc.).

In [44]:
def my_spiral_ones(n):

  # base case: if n == 1 then return 1
  if n == 1:
    arr = np.array([1])
  
  else:
    # all of the directions for the ones. the order is right, then down, then left, then up and then right
    directions = ['right', 'down', 'left', 'up']
    
    # There will be a total of n-1 rounds to get to a matrix n by n. We thus want to extract the (n-1)th element from directions. 
    # So, for example if n = 5 then:
    # we start with n = 2 by appending 1's to the right of a 2 by 2 matrix, then for n = 3 we append 1's below a 3 by 3 matrix,
    # then for n = 4 we append 1's to the left of a 4 by 4 matrix. Finally, for n = 5 we append 1's to the top of a 5 by 5 matrix.
    # Thus, to get to 5 by 5 we performed 4 operations. However, if n > 4, say 7 then we need to perform 6 operations in the 
    # following order: right --> down --> left --> up --> right --> down. Thus, we get to down, which is the second element of 
    # directions list. To account for zero indexing we thus extract ((n - 2) % 4)th element, which in this case is ((7-2) % 4) = 1.
    direction = directions[(n-2) % 4]

    if direction == 'right':
      # first recursive case: if final direction is right to get to n by n then for right we take the array at previous step
      # and append an array of 1's of size n to the right of the (n-1, n-1) matrix. However, we need to first append an array
      # of size n-1 at the bottom of the matrix from previous step (n-1, n-1) to get a valid n by n matrix. vstack would append
      # arrays on top of each other and hstack would append arrays side by side. Thus, we append the matrix at previous step on top
      # of zeros and then append that matrix with an array of 1's side by side to get the final n by n matrix.
      # e.g. if n = 2 then we have [1] from the previous step and thus first we get 
      # [[1]   and then  [[1,1]]
      #  [0]]            [[0,1]] 
      arr = np.hstack([np.vstack([my_spiral_ones(n-1), np.zeros(n-1)]), np.ones(((n-1)+1,1))])

      # second recursive case: if final direction is down then first append an array of 0's to the left of (n-1, n-1) matrix
      # and then stack that matrix on top of an array of 1's of size n to get the n by n matrix.
      # e.g. if n = 3 then we have the 2 by 2 array computed above.
      # [[0]] + [[1,1]] = [[0,1,1]] 
      # [[0]]   [[0,1]]   [[0,0,1]]
      #                 + [[1,1,1]]
    elif direction == 'down':
      arr = np.vstack([np.hstack([np.zeros(n-1).reshape(-1,1), my_spiral_ones(n-1)]), np.ones(((n-1)+1))])
    
      # third recursive case: place an array of 0's at the top of the n-1 by n-1 matrix and then concatenate 
      # an array of 1's of size n with that matrix to get an n by n matrix
      # e.g. if n = 4 then we have the 3 by 3 matrix from above.
      # [[1]]   [[0,0,0]] = [[1,0,0,0]] 
      # [[1]] + [[0,1,1]]   [[1,0,1,1]]
      # [[1]]   [[0,0,1]]   [[1,0,0,1]]
      # [[1]]   [[1,1,1]]   [[1,1,1,1]]
    elif direction == 'left':
      arr = np.hstack([np.ones(((n-1)+1)).reshape(-1,1), np.vstack([np.zeros(n-1), my_spiral_ones(n-1)])])

      # fourth recursive case: place an array of 0's to the right of n-1 by n-1 matrix and then stack 
      # an array of 1's on top of that matrix to get the n by n matrix
      # e.g. n = 5. We have the 4 by 4 matrix from above
      #                         [[1,1,1,1,1]]
      # [[1,0,0,0]] + [[0]] = + [[1,0,0,0,0]]  
      # [[1,0,1,1]]   [[0]]     [[1,0,1,1,0]]
      # [[1,0,0,1]]   [[0]]     [[1,0,0,1,0]]
      # [[1,1,1,1]]   [[0]]     [[1,1,1,1,0]]
    elif direction == 'up':
      arr = np.vstack([np.ones(((n-1)+1)), np.hstack([my_spiral_ones(n-1), np.zeros(n-1).reshape(-1,1)])])

  return arr

In [45]:
# Output: array([1])
my_spiral_ones(1)

array([1])

In [46]:
# Output: 
# array([[1, 1],
#       [0, 1]])
my_spiral_ones(2)

array([[1., 1.],
       [0., 1.]])

In [47]:
# Output:
#array([[0, 1, 1],
#       [0, 0, 1],
#       [1, 1, 1]])
my_spiral_ones(3)

array([[0., 1., 1.],
       [0., 0., 1.],
       [1., 1., 1.]])

In [48]:
# Output:
#array([[1, 0, 0, 0],
#       [1, 0, 1, 1],
#       [1, 0, 0, 1],
#       [1, 1, 1, 1]])
my_spiral_ones(4)

array([[1., 0., 0., 0.],
       [1., 0., 1., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [49]:
# Output:
#array([[1, 1, 1, 1, 1],
#       [1, 0, 0, 0, 0],
#       [1, 0, 1, 1, 0],
#       [1, 0, 0, 1, 0],
#       [1, 1, 1, 1, 0]])
my_spiral_ones(5)

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0.],
       [1., 0., 1., 1., 0.],
       [1., 0., 0., 1., 0.],
       [1., 1., 1., 1., 0.]])

__Checking the operations from 1 to 13 to complete 12 operations.__

In [50]:
operations = ['right', 'down', 'left', 'up'] * 3

for num in range(1, 14):
  print(num)
  if num > 1:
    print(operations[num-2])
  print(my_spiral_ones(num))
  print('='*100)
  print()

1
[1]

2
right
[[1. 1.]
 [0. 1.]]

3
down
[[0. 1. 1.]
 [0. 0. 1.]
 [1. 1. 1.]]

4
left
[[1. 0. 0. 0.]
 [1. 0. 1. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]

5
up
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0.]
 [1. 0. 1. 1. 0.]
 [1. 0. 0. 1. 0.]
 [1. 1. 1. 1. 0.]]

6
right
[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 1. 1. 0. 1.]
 [1. 0. 0. 1. 0. 1.]
 [1. 1. 1. 1. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]

7
down
[[0. 1. 1. 1. 1. 1. 1.]
 [0. 1. 0. 0. 0. 0. 1.]
 [0. 1. 0. 1. 1. 0. 1.]
 [0. 1. 0. 0. 1. 0. 1.]
 [0. 1. 1. 1. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]

8
left
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 0. 0. 0. 1.]
 [1. 0. 1. 0. 1. 1. 0. 1.]
 [1. 0. 1. 0. 0. 1. 0. 1.]
 [1. 0. 1. 1. 1. 1. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]

9
up
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 1. 1. 1. 1. 1. 0.]
 [1. 0. 1. 0. 0. 0. 0. 1. 0.]
 [1. 0. 1. 0. 1. 1. 0. 1. 0.]
 [1. 0. 1. 0. 0. 1. 0. 1. 0.]
 [1. 0. 1. 1. 1. 1. 0. 1. 0.]
 

10. Rewrite my_spiral_ones without using recursion.

In [51]:
def my_spiral_ones(n):

  # if n is 1 then return 1
  if n == 1:
    return 1

  arr = np.array([1]) # start with an array of just 1
  prev_size = 1 # this keeps track of the previous array size
  direction = 'right' # start with right

  # keep performing the eoperations till we get n by n matrix
  while prev_size < n:

    # for right, first add an array of 0's of prev_size at the bottom and then add an array of size (prev_size + 1) to the right  
    if direction == 'right':
      arr = np.hstack([np.vstack([arr, np.zeros(prev_size)]), np.ones((prev_size+1,1))])
      direction = 'down'
      prev_size += 1

    # for down, first add an array of 0's of prev_size to the left and then add an array of 1's of size (prev_size + 1) at the bottom
    elif direction == 'down':
      arr = np.vstack([np.hstack([np.zeros(prev_size).reshape(-1,1), arr]), np.ones((prev_size+1))])
      direction = 'left'
      prev_size += 1
    
    # for left, first add an array of 0's of prev_size to the top and then add an array of 1's of size (prev_size + 1) to the left
    elif direction == 'left':
      arr = np.hstack([np.ones((prev_size+1)).reshape(-1,1), np.vstack([np.zeros(prev_size), arr])])
      direction = 'up'
      prev_size += 1

    # for up, first add an array of 0's of prev_size to the right and then add an array of 1's of size (prev_size + 1) at the top
    elif direction == 'up':
      arr = np.vstack([np.ones((prev_size+1)), np.hstack([arr, np.zeros(prev_size).reshape(-1,1)])])
      direction = 'right'
      prev_size += 1

  return arr

In [52]:
# Output: 1
my_spiral_ones(1)

1

In [53]:
# Output: 
# array([[1, 1],
#       [0, 1]])
my_spiral_ones(2)

array([[1., 1.],
       [0., 1.]])

In [54]:
# Output:
#array([[0, 1, 1],
#       [0, 0, 1],
#       [1, 1, 1]])
my_spiral_ones(3)

array([[0., 1., 1.],
       [0., 0., 1.],
       [1., 1., 1.]])

In [55]:
# Output:
#array([[1, 0, 0, 0],
#       [1, 0, 1, 1],
#       [1, 0, 0, 1],
#       [1, 1, 1, 1]])
my_spiral_ones(4)

array([[1., 0., 0., 0.],
       [1., 0., 1., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [56]:
# Output:
#array([[1, 1, 1, 1, 1],
#       [1, 0, 0, 0, 0],
#       [1, 0, 1, 1, 0],
#       [1, 0, 0, 1, 0],
#       [1, 1, 1, 1, 0]])
my_spiral_ones(5)

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0.],
       [1., 0., 1., 1., 0.],
       [1., 0., 0., 1., 0.],
       [1., 1., 1., 1., 0.]])

In [57]:
operations = ['right', 'down', 'left', 'up'] * 3

for num in range(1, 14):
  print(num)
  if num > 1:
    print(operations[num-2])
  print(my_spiral_ones(num))
  print('='*100)
  print()

1
1

2
right
[[1. 1.]
 [0. 1.]]

3
down
[[0. 1. 1.]
 [0. 0. 1.]
 [1. 1. 1.]]

4
left
[[1. 0. 0. 0.]
 [1. 0. 1. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]

5
up
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0.]
 [1. 0. 1. 1. 0.]
 [1. 0. 0. 1. 0.]
 [1. 1. 1. 1. 0.]]

6
right
[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 1. 1. 0. 1.]
 [1. 0. 0. 1. 0. 1.]
 [1. 1. 1. 1. 0. 1.]
 [0. 0. 0. 0. 0. 1.]]

7
down
[[0. 1. 1. 1. 1. 1. 1.]
 [0. 1. 0. 0. 0. 0. 1.]
 [0. 1. 0. 1. 1. 0. 1.]
 [0. 1. 0. 0. 1. 0. 1.]
 [0. 1. 1. 1. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]

8
left
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 0. 0. 0. 0. 1.]
 [1. 0. 1. 0. 1. 1. 0. 1.]
 [1. 0. 1. 0. 0. 1. 0. 1.]
 [1. 0. 1. 1. 1. 1. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]

9
up
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 1. 1. 1. 1. 1. 0.]
 [1. 0. 1. 0. 0. 0. 0. 1. 0.]
 [1. 0. 1. 0. 1. 1. 0. 1. 0.]
 [1. 0. 1. 0. 0. 1. 0. 1. 0.]
 [1. 0. 1. 1. 1. 1. 0. 1. 0.]
 [1

11. Draw the recursion tree for my_towers.

In [58]:
# my_towers function from the notebook
# link: https://pythonnumericalmethods.berkeley.edu/notebooks/chapter06.02-Divide-and-Conquer.html
def my_towers(N, from_tower, to_tower, alt_tower):
    """
    Displays the moves required to move a tower of size N from the
    'from_tower' to the 'to_tower'. 
    
    'from_tower', 'to_tower' and 'alt_tower' are uniquely either 
    1, 2, or 3 referring to tower 1, tower 2, and tower 3. 
    """
    
    if N != 0:
        # recursive call that moves N-1 stack from starting tower
        # to alternate tower
        my_towers(N-1, from_tower, alt_tower, to_tower)
        
        # display to screen movement of bottom disk from starting
        # tower to final tower
        print("Move disk %d from tower %d to tower %d."\
                  %(N, from_tower, to_tower))
        
        # recursive call that moves N-1 stack from alternate tower
        # to final tower
        my_towers(N-1, alt_tower, to_tower, from_tower)

my_towers(3, 1, 3, 2)

Move disk 1 from tower 1 to tower 3.
Move disk 2 from tower 1 to tower 2.
Move disk 1 from tower 3 to tower 2.
Move disk 3 from tower 1 to tower 3.
Move disk 1 from tower 2 to tower 1.
Move disk 2 from tower 2 to tower 3.
Move disk 1 from tower 1 to tower 3.


__explaining the recursion:__

input: N = 3, from_tower = 1, to_tower = 3, alt_tower = 2.

__note:__ first recursive call before the print statement moves the disk __from_tower__ to __alt_tower__ and thus we swap second and third arguments i.e. __to_tower__ = __alt_tower__ and __alt_tower__ = __to_tower__. In the above example it would become N = 2, __from_tower__ = 1, __to_tower__ = 2, __alt_tower__ = 3.

Similarly, second recursive call after the print statement moves the disk from __alt_tower__ to __to_tower__. Here, __from_tower__ = __alt_tower__ and __alt_tower__ = __from_tower__. In the above example it would become N = 2, __from_tower__ = 2, __to_tower__ = 3, __alt_tower__ = 1.

---------------------------------------------------------------------------

my_towers(N = 3, from_tower = 1, to_tower = 3, alt_tower = 2) __(call 0)__

__First iteration:__

N != 0

__swap to_tower and alt_tower__ <br>
my_towers(N = 2, from_tower = 1, to_tower = 2, alt_tower = 3) __(call 1)__

__Second iteration:__

input: my_towers(N = 2, from_tower = 1, to_tower = 2, alt_tower = 3):

N != 0

my_towers(N = 1, from_tower = 1, to_tower = 3, alt_tower = 2) __(call 2)__

__Third iteration:__

input: my_towers(N = 1, from_tower = 1, to_tower = 3, alt_tower = 2):

N != 0

my_towers(N = 0, from_tower = 1, to_tower = 3, alt_tower = 2) __(call 3)__

__Fourth iteration:__

input: my_towers(N = 0, from_tower = 1, to_tower = 3, alt_tower = 2)

N == 0

nothing else happens. Now we got to the base case. Now, we start with print statement of __call 2__ and move to the second recursive function in __call 2__.

__print("Move disk 1 from tower 1 to tower 3.")__

__swap from_tower and alt_tower from call 2__ <br>
my_towers(N = 0, from_tower = 2, to_tower = 3, alt_tower = 1) __(call 4)__


__Fifth iteration:__

input: my_towers(N = 0, from_tower = 2, to_tower = 3, alt_tower = 1)

N == 0

now we finished both the recursive calls of N = 1 and so now we move to __call 1__ print statement and pass it to the second recursive function.

__print("Move disk 2 from tower 1 to tower 2.")__

my_towers(N = 1, from_tower = 3, to_tower = 2, alt_tower = 1) __(call 5)__


__Sixth iteration:__

input: my_towers(N = 1, from_tower = 3, to_tower = 2, alt_tower = 1)

N != 0

my_towers(N = 0, from_tower = 3, to_tower = 1, alt_tower = 2) __(call 6)__


__Seventh iteration:__

input: my_towers(N = 0, from_tower = 3, to_tower = 1, alt_tower = 2)

N == 0

now we execute print statement for __call 5__

__print("Move disk 1 from tower 3 to tower 2.")__

my_towers(N = 0, from_tower = 1, to_tower = 2, alt_tower = 3) __(call 7)__

__Eighth iteration:__

input: my_towers(N = 0, from_tower = 1, to_tower = 2, alt_tower = 3)

N == 0

here, we finish both recursive calls of N = 2 and thus the first recursive call of the original input is finished. Now, we execute the print statement of our original input __call 0__ and move that to the second recursive call.

__print("Move disk 3 from tower 1 to tower 3.")__

my_towers(N = 2, from_tower = 2, to_tower = 3, alt_tower = 1) __(call 8)__

__ninth iteration:__

input: my_towers(N = 2, from_tower = 2, to_tower = 3, alt_tower = 1)

N != 0

my_towers(N = 1, from_tower = 2, to_tower = 1, alt_tower = 3) __(call 9)__

__tenth iteration:__

input: my_towers(N = 1, from_tower = 2, to_tower = 1, alt_tower = 3)

N != 0

my_towers(N = 0, from_tower = 2, to_tower = 3, alt_tower = 1) __(call 10)__

__eleventh iteration:__

input: my_towers(N = 0, from_tower = 2, to_tower = 3, alt_tower = 1)

N == 0

since we reached 0, we execute the print statement of __call 9__ and move it to the second recursive function.

__print("Move disk 1 from tower 2 to tower 1.")__

my_towers(N = 0, from_tower = 3, to_tower = 2, alt_tower = 1) __(call 11)__

__twelveth:__

input: my_towers(N = 0, from_tower = 3, to_tower = 2, alt_tower = 1)

N == 0

we reached 0 in both recursive functions for N = 1 and so we now execute the print statement of __call 8__ with N = 2 and pass it to the second recursive function.

__print("Move disk 2 from tower 2 to tower 3.")__

my_towers(N = 1, from_tower = 1, to_tower = 3, alt_tower = 2) __(call 12)__

__thirteenth:__

input: my_towers(N = 1, from_tower = 1, to_tower = 3, alt_tower = 2)

N != 0

my_towers(N = 0, from_tower = 1, to_tower = 2, alt_tower = 3) __(call 13)__

__fourteenth:__

input: my_towers(N = 0, from_tower = 1, to_tower = 2, alt_tower = 3)

N == 0

now we execute the print statement of __call 12__ and pass it to the second recursive function.

__print("Move disk 1 from tower 1 to tower 3.")__

my_towers(N = 0, from_tower = 2, to_tower = 3, alt_tower = 1) __(call 14)__

Here, we reached the end as after this call all recursive calls each side have been done so the program has been completed.

------------------------------------------------------------------------

__Recursion tree of the tower of hanoi__

__first argument:__ N (disk no.)<br>
__second argument:__ from_tower <br>
__third argument:__ to_tower <br>
__fourth argument:__ from_tower 

<pre>
                                      (0)
                                  (3, 1, 3, 2)
                 (1)                                       (8)
              (2,1,2,3)                                 (2,2,3,1)

       (2)                 (5)                   (9)                (12)
    (1,1,3,2)           (1,3,2,1)             (1,2,1,3)           (1,1,3,2)

  (3)       (4)       (6)       (7)         (10)      (11)      (13)      (14)
(0,...)   (0,...)   (0,...)   (0,...)     (0,...)   (0,...)   (0,...)   (0,...)
               
</pre>

 (3): print("Move disk 1 from tower 1 to tower 3.") <br>
 (4): print("Move disk 2 from tower 1 to tower 2.") <br>
 (6): print("Move disk 1 from tower 3 to tower 2.") <br>
 (7): print("Move disk 3 from tower 1 to tower 3.") <br>
(10): print("Move disk 1 from tower 2 to tower 1.") <br>
(11): print("Move disk 2 from tower 2 to tower 3.") <br>
(13): print("Move disk 1 from tower 1 to tower 3.") <br>
(14): Final call after which the program run is completed.


12. Rewrite the Towers of Hanoi function in this chapter without using recursion.

In [59]:
def tower_hanoi(n, source, target, aux):

  # input is a list that will keep track of all the inputs that are being passed in
  input = [(n,source,target,aux)]

  # indicator_dict is a dictionary where the key is an input that has been processed and a list of two elements 
  # indicating whether the input has passed through both the operations. So, for example if input is (2,1,3,2)
  # then it needs to first swop to and alt (1,1,2,3) and then swop from and alt (1,2,3,1). If both of these have
  # been processed then we get {(2,1,3,2): [1,1]} indicating it has passed through both recursive operations.  
  indicator_dict = {(n,source,target,aux): [0,1]} # root only has to run from the left
  
  n_ops = 0 # n_ops to keep track of number of iterations performed
  N = n # keeping track of the original number of disks
  root = (n,source,target,aux) # this is the root that will pass through the iteration twice, one in between and one at the end
  root_process = 0 # this keeps track of whther the root has been passed through the print statement.

  while input:

      # if several operations have been passed and we get to the root then it means the program has passed through the left branch.
      # Thus, we remove all other prior operations 2 levels
      # below the root. If original n = 3 then remove all branches with n = 1. This allows us to re-process same branches
      # to the right side of the root.
      if n_ops > 0 and input[-1] == root:
          indicator_dict = {k:v for (k,v) in indicator_dict.items() if k[0] >= N-1}

      # take the last value in input list as initial argument    
      n, source, target, aux = input[-1]

      # this first while loop mimicks the first recursive function, which is to replace to_tower and alt_tower till we get to 0
      while n > 1:
        new_input = (n-1, source, aux, target)

        # here, if new_input has been processed before from the same branch then we will not reprocess it. That would indicate
        # that all branches and sub-branches have been processed and thus we terminate the loop. However, if the previous branch 
        # has indicator [0,0] then the same input is coming from a different branch and thus we would recreate this input with [0,0]
        if new_input not in indicator_dict or sum(indicator_dict[input[-1]]) == 0:
            input.append(new_input)
            indicator_dict[new_input] = [0,0]

        else:
            break

        n, source, target, aux = new_input

      # if the last input is the root and it has been processed already then we do not print it again
      if input[-1] != root or root_process == 0:
        # if the input has an indicator [1,1] then all the sub-branches on both sides have been processed and we do not print it again
        if sum(indicator_dict[input[-1]]) < 2:
          print(f"Move disk {n} from {source} to {target}")

      # this will keep a track of how many times the root has been processed
      if input[-1] == root:
        root_process += 1

      # once the input is printed we activate the left indicator by replacing a [0,0] with [1,0]
      if indicator_dict[(n, source, target, aux)][0] == 0:
        indicator_dict[(n, source, target, aux)][0] = 1

      # if the input that was printed has n > 1 then we pass it to the second recursive function or move to the right of the 
      # branch by replacing from_tower and alt_tower
      if n > 1:
        new_input = (n-1, aux, target, source)

        # if this new_input is in indicator_dict, then it means it has already been processed and we don't need to reprocess it.
        # However, if the input has indicator [1,0] then it means it's to the right of a different branch and thus, we will
        # replace it in the indicator with [0,0] and reprocess it.
        if new_input not in indicator_dict:
          input.append(new_input)
          indicator_dict[new_input] = [0,0]

        else:
          if len(input) > 1:
            if indicator_dict[input[-1]][0] == 1 and indicator_dict[input[-1]][1] == 0:
              input.append(new_input)
              indicator_dict[new_input] = [0,0]

      # if the input has been printed and passed through both recursive functions then it would have indicator
      # [1,0] at this point and thus we turn the right indicator on and make it [1,1] 
      if indicator_dict[input[-1]][0] == 1 and indicator_dict[input[-1]][-1] == 0:
          indicator_dict[input[-1]][-1] = 1

      # if indicator of this input is [1,1] then we delete it from the input list
      if sum(indicator_dict[input[-1]]) == 2:
          input.pop(-1)
          
          # if the previous input is deleted and there are still inputs left then if the next one is a branch and is
          # [0,0] then we change it to [1,0] indicating we passed through the left side of the branch. If the prevous 
          # input is [1,0] then we change it to [1,1] 
          if len(input) > 0:
            if sum(indicator_dict[input[-1]]) == 0:
              indicator_dict[input[-1]] = [1,0]
            
            else:
              # it could happen that we have at this point successfully passed through multiple branches at this point
              # so all previous branches that are [1,0] will be converted to [1,1] to indicate we have passed through the right side 
              # of the branch
              for i in input[::-1]:
                if indicator_dict[i][0] == 1 and indicator_dict[i][1] == 0:
                    indicator_dict[i] = [1,1]
                else:
                    break

      n_ops += 1 # increment the n_ops at this point

In [60]:
my_towers(3, 1, 3, 2)

Move disk 1 from tower 1 to tower 3.
Move disk 2 from tower 1 to tower 2.
Move disk 1 from tower 3 to tower 2.
Move disk 3 from tower 1 to tower 3.
Move disk 1 from tower 2 to tower 1.
Move disk 2 from tower 2 to tower 3.
Move disk 1 from tower 1 to tower 3.


In [61]:
tower_hanoi(3,1,3,2)

Move disk 1 from 1 to 3
Move disk 2 from 1 to 2
Move disk 1 from 3 to 2
Move disk 3 from 1 to 3
Move disk 1 from 2 to 1
Move disk 2 from 2 to 3
Move disk 1 from 1 to 3


In [62]:
my_towers(4, 1, 3, 2)

Move disk 1 from tower 1 to tower 2.
Move disk 2 from tower 1 to tower 3.
Move disk 1 from tower 2 to tower 3.
Move disk 3 from tower 1 to tower 2.
Move disk 1 from tower 3 to tower 1.
Move disk 2 from tower 3 to tower 2.
Move disk 1 from tower 1 to tower 2.
Move disk 4 from tower 1 to tower 3.
Move disk 1 from tower 2 to tower 3.
Move disk 2 from tower 2 to tower 1.
Move disk 1 from tower 3 to tower 1.
Move disk 3 from tower 2 to tower 3.
Move disk 1 from tower 1 to tower 2.
Move disk 2 from tower 1 to tower 3.
Move disk 1 from tower 2 to tower 3.


In [63]:
tower_hanoi(4,1,3,2)

Move disk 1 from 1 to 2
Move disk 2 from 1 to 3
Move disk 1 from 2 to 3
Move disk 3 from 1 to 2
Move disk 1 from 3 to 1
Move disk 2 from 3 to 2
Move disk 1 from 1 to 2
Move disk 4 from 1 to 3
Move disk 1 from 2 to 3
Move disk 2 from 2 to 1
Move disk 1 from 3 to 1
Move disk 3 from 2 to 3
Move disk 1 from 1 to 2
Move disk 2 from 1 to 3
Move disk 1 from 2 to 3


In [64]:
my_towers(5, 1, 3, 2)

Move disk 1 from tower 1 to tower 3.
Move disk 2 from tower 1 to tower 2.
Move disk 1 from tower 3 to tower 2.
Move disk 3 from tower 1 to tower 3.
Move disk 1 from tower 2 to tower 1.
Move disk 2 from tower 2 to tower 3.
Move disk 1 from tower 1 to tower 3.
Move disk 4 from tower 1 to tower 2.
Move disk 1 from tower 3 to tower 2.
Move disk 2 from tower 3 to tower 1.
Move disk 1 from tower 2 to tower 1.
Move disk 3 from tower 3 to tower 2.
Move disk 1 from tower 1 to tower 3.
Move disk 2 from tower 1 to tower 2.
Move disk 1 from tower 3 to tower 2.
Move disk 5 from tower 1 to tower 3.
Move disk 1 from tower 2 to tower 1.
Move disk 2 from tower 2 to tower 3.
Move disk 1 from tower 1 to tower 3.
Move disk 3 from tower 2 to tower 1.
Move disk 1 from tower 3 to tower 2.
Move disk 2 from tower 3 to tower 1.
Move disk 1 from tower 2 to tower 1.
Move disk 4 from tower 2 to tower 3.
Move disk 1 from tower 1 to tower 3.
Move disk 2 from tower 1 to tower 2.
Move disk 1 from tower 3 to tower 2.
M

In [65]:
tower_hanoi(5,1,3,2)

Move disk 1 from 1 to 3
Move disk 2 from 1 to 2
Move disk 1 from 3 to 2
Move disk 3 from 1 to 3
Move disk 1 from 2 to 1
Move disk 2 from 2 to 3
Move disk 1 from 1 to 3
Move disk 4 from 1 to 2
Move disk 1 from 3 to 2
Move disk 2 from 3 to 1
Move disk 1 from 2 to 1
Move disk 3 from 3 to 2
Move disk 1 from 1 to 3
Move disk 2 from 1 to 2
Move disk 1 from 3 to 2
Move disk 5 from 1 to 3
Move disk 1 from 2 to 1
Move disk 2 from 2 to 3
Move disk 1 from 1 to 3
Move disk 3 from 2 to 1
Move disk 1 from 3 to 2
Move disk 2 from 3 to 1
Move disk 1 from 2 to 1
Move disk 4 from 2 to 3
Move disk 1 from 1 to 3
Move disk 2 from 1 to 2
Move disk 1 from 3 to 2
Move disk 3 from 1 to 3
Move disk 1 from 2 to 1
Move disk 2 from 2 to 3
Move disk 1 from 1 to 3


In [66]:
my_towers(4, 1, 2, 3)

Move disk 1 from tower 1 to tower 3.
Move disk 2 from tower 1 to tower 2.
Move disk 1 from tower 3 to tower 2.
Move disk 3 from tower 1 to tower 3.
Move disk 1 from tower 2 to tower 1.
Move disk 2 from tower 2 to tower 3.
Move disk 1 from tower 1 to tower 3.
Move disk 4 from tower 1 to tower 2.
Move disk 1 from tower 3 to tower 2.
Move disk 2 from tower 3 to tower 1.
Move disk 1 from tower 2 to tower 1.
Move disk 3 from tower 3 to tower 2.
Move disk 1 from tower 1 to tower 3.
Move disk 2 from tower 1 to tower 2.
Move disk 1 from tower 3 to tower 2.


In [67]:
tower_hanoi(4,1,2,3)

Move disk 1 from 1 to 3
Move disk 2 from 1 to 2
Move disk 1 from 3 to 2
Move disk 3 from 1 to 3
Move disk 1 from 2 to 1
Move disk 2 from 2 to 3
Move disk 1 from 1 to 3
Move disk 4 from 1 to 2
Move disk 1 from 3 to 2
Move disk 2 from 3 to 1
Move disk 1 from 2 to 1
Move disk 3 from 3 to 2
Move disk 1 from 1 to 3
Move disk 2 from 1 to 2
Move disk 1 from 3 to 2


working through how the iterative version is working

input: (3,1,3,2)

input = [(3,1,3,2)]

indicator_dict = {(3,1,3,2): [0,1]} <br>
n_ops = 0 <br>
N = n <br>
root = (3,1,3,2) <br>
root_process = 0 

now we enter the loop:

input list is not empty so we continue

__iteration 1:__

__take the last value in input list as initial argument__ <br>   
n, source, target, aux = (3,1,3,2)

n_ops == 0 so we do not modify the dictionary

now we enter the first recursive function mimicked by the while loop.

__we swop to_tower and alt_tower__ <br>
new_input = (2,1,2,3)

__append to input list and add to indicator_dict__ <br>
input = [(3,1,3,2), (2,1,2,3)]

indicator_dict = {(3,1,3,2): [0,1], (2,1,2,3): [0,0]}

__n > 1 so we continue the above operations__

new_input = (1,1,3,2)

input = [(3,1,3,2), (2,1,2,3), (1,1,3,2)]

indicator_dict = {(3,1,3,2): [0,1], (2,1,2,3): [0,0], (1,1,3,2): [0,0]}

__n = 1 so we exit the loop as the next n-1 would be 0__

__input is not the root and its indicators are not [1,1] so we print__

print('Move disk 1 from 1 to 3.')

__now we activate the left key__ <br>
indicator_dict = {(3,1,3,2): [0,1], (2,1,2,3): [0,0], (1,1,3,2): [1,0]}

__n is not greater than 1 so we do not pass it to the right as the next n-1 to the right is 0 and so we have reached the end. Hence, we turn on the right indicator.__ <br>
indicator_dict = {(3,1,3,2): [0,1], (2,1,2,3): [0,0], (1,1,3,2): [1,1]}

__since indicator is [1,1], we delete the input__ <br>
input = [(3,1,3,2), (2,1,2,3)]
      
__(2,1,2,3) has indicators [0,0] and so we turn it to [1,0] as we have passed to the left of (2,1,2,3)__ <br>
indicator_dict = {(3,1,3,2): [0,1], (2,1,2,3): [1,0], (1,1,3,2): [1,1]}
      

__increment n_ops by 1 as we reached the end__ <br>
n_ops = 1

---------------------------------------------------------------------------

__iteration 2:__

__take the last value in input list as initial argument__ <br>   
n, source, target, aux = (2,1,2,3)

n_ops == 1 and the next input is not the root so we do not modify the dictionary

now we enter the first recursive function mimicked by the while loop.

__we swop to_tower and alt_tower__ <br>
new_input = (1,1,3,2)

__new_input is in indicator_dict and both indicators of current input are not 0, and so we break out of this loop as we have already passed through the left of (2,1,2,3)__

__input is not the root and its indicators are not [1,1] so we print__

print('Move disk 2 from 1 to 2.')

__here the left key is already activated.__ <br>
indicator_dict = {(3,1,3,2): [0,1], (2,1,2,3): [1,0], (1,1,3,2): [1,1]}

__n is greater than 1 so we enter the right side of the input.__ <br>

__we now swop from_tower and alt_tower__ <br>
new_input = (1,3,2,1)

input = input = [(3,1,3,2), (2,1,2,3), (1,3,2,1)] <br>
indicator_dict = {(3,1,3,2): [0,1], (2,1,2,3): [1,0], (1,1,3,2): [1,1], (1,3,2,1): [0,0]}

__since indicator is not [1,1], we do nothing else__ <br>      

__increment n_ops by 1 as we reached the end__ <br>
n_ops = 2

------------------------------------------------------------------------

__iteration 3:__

__take the last value in input list as initial argument__ <br>   
n, source, target, aux = (1,3,2,1)

n_ops == 2 and the next input is not the root so we do not modify the dictionary

since n is not greater than 1 we do not enter the first loop.

__input is not the root and its indicators are not [1,1] so we print__

print('Move disk 1 from 3 to 2.')

__now we activate the left indicator.__ <br>
indicator_dict = {(3,1,3,2): [0,1], (2,1,2,3): [1,0], (1,1,3,2): [1,1], (1,3,2,1): [1,0]}

__n is not greater than 1 and so we do not enter the right side as we are at the end.__ <br>

__now we turn on the right indicator.__
indicator_dict = {(3,1,3,2): [0,1], (2,1,2,3): [1,0], (1,1,3,2): [1,1], (1,3,2,1): [1,1]}

__since indicator is [1,1], we delete the input__ <br>
input = [(3,1,3,2), (2,1,2,3)]

__(2,1,2,3) has indicator [1,0] and so we turn it to [1,1] as we have passed both sides of (2,1,2,3). we then check the previousone (3,1,3,2) where the left indicator is 0 and so we stop.__      
indicator_dict = {(3,1,3,2): [0,1], (2,1,2,3): [1,1], (1,1,3,2): [1,1], (1,3,2,1): [1,1]}

__increment n_ops by 1 as we reached the end__ <br>
n_ops = 3

------------------------------------------------------------------------

__iteration 4:__

__take the last value in input list as initial argument__ <br>   
n, source, target, aux = (2,1,2,3)

n_ops == 3 and the next input is not the root so we do not modify the dictionary

since n is greater than 1 we enter the first loop.

__we swop to_tower and alt_tower__ <br>
new_input = (1,1,3,2)

__new_input is in indicator_dict and both indicators of current input are not 0, and so we break out of this loop as we have already passed through the left of (2,1,2,3)__

__input is not the root but the indicators are [1,1] so we do not print__

__the left indicator is already 1.__ <br>

__n is greater than 1 and so we enter the right side__<br>

__we now swop from_tower and alt_tower__ <br>
new_input = (1,3,2,1)

__new_input is in indicator_dict and the right indicator of current input is not 0 and so we move on.__

__right indicator is already 1.__

__since indicator is [1,1], we delete the input__ <br>
input = [(3,1,3,2)]

__For (3,1,3,2) is not [0,0] or [1,0]. It is at initial se value [0,1] as the root only has to run from the left. Thus, the program leaves it as is.__      

__increment n_ops by 1 as we reached the end__ <br>
n_ops = 4

---------------------------------------------------------------------------

__iteration 5:__

__take the last value in input list as initial argument__ <br>   
n, source, target, aux = (3,1,3,2)

n_ops == 4 and the next input is the root so we remove all branches below N - 1, where N is the original number of disks.

indicator_dict = {(3,1,3,2): [0,1], (2,1,2,3): [1,1]}

now we enter the first recursive function mimicked by the while loop.

__we swop to_tower and alt_tower__ <br>
new_input = (2,1,2,3)

__new_input is in indicator_dict and both indicators of current input are not 0, and so we break out of this loop as we have already passed through the left of (2,1,2,3)__

__input is the root but its indicators are not [1,1] so we print__

print('Move disk 3 from 1 to 3.')

__now we activate the left key.__ <br>
indicator_dict = {(3,1,3,2): [1,1], (2,1,2,3): [1,1]}

__n is greater than 1 so we enter the right side of the input.__ <br>

__we now swop from_tower and alt_tower__ <br>
new_input = (2,2,3,1)

input = [(3,1,3,2), (2,2,3,1)] <br>
indicator_dict = {(3,1,3,2): [1,1], (2,1,2,3): [1,1], (2,2,3,1): [0,0]}

__since indicator is not [1,1], we do nothing else__ <br>      

__increment n_ops by 1 as we reached the end__ <br>
n_ops = 5

---------------------------------------------------------------------------

__iteration 6:__

__take the last value in input list as initial argument__ <br>   
n, source, target, aux = (2,2,3,1)

input is not root n_ops == 5 so we do not modify the dictionary

since n > 1, we enter the first recursive function.

__we swop to_tower and alt_tower__ <br>
new_input = (1,2,1,3)

__append to input list and add to indicator_dict__ <br>
input = [(3,1,3,2), (2,2,3,1), (1,2,1,3)]

indicator_dict = {(3,1,3,2): [1,1], (2,1,2,3): [1,1], (2,2,3,1): [0,0], (1,2,1,3): [0,0]}

__n = 1 so we exit the loop as the next n-1 would be 0__

__input is not the root and its indicators are not [1,1] so we print__

print('Move disk 1 from 2 to 1.')

__now we activate the left key__ <br>
indicator_dict = {(3,1,3,2): [1,1], (2,1,2,3): [1,1], (2,2,3,1): [0,0], (1,2,1,3): [1,0]}

__n is not greater than 1 so we do not pass it to the right as the next n-1 to the right is 0 and so we have reached the end. Hence, we turn on the right indicator.__ <br>
indicator_dict = {(3,1,3,2): [1,1], (2,1,2,3): [1,1], (2,2,3,1): [0,0], (1,2,1,3): [1,1]}

__since indicator is [1,1], we delete the input__ <br>
input = [(3,1,3,2), (2,2,3,1)]
      
__(2,2,3,1) has indicators [0,0] and so we turn it to [1,0] as we have passed to the left of (2,2,3,1)__ <br>
indicator_dict = {(3,1,3,2): [1,1], (2,1,2,3): [1,1], (2,2,3,1): [1,0], (1,2,1,3): [1,1]}
      
__increment n_ops by 1 as we reached the end__ <br>
n_ops = 6

---------------------------------------------------------------------------

__iteration 7:__

__take the last value in input list as initial argument__ <br>   
n, source, target, aux = (2,2,3,1)

n_ops == 6 and the next input is not the root so we do nothing.

now we enter the first recursive function.

__we swop to_tower and alt_tower__ <br>
new_input = (1,2,1,3)

__new_input is in indicator_dict and both indicators of current input are not 0, and so we break out of this loop as we have already passed through the left of (2,2,3,1)__

__input is the root but its indicators are not [1,1] so we print__

print('Move disk 2 from 2 to 3.')

__left key is already activated.__ <br>

__n is greater than 1 so we enter the right side of the input.__ <br>

__we now swop from_tower and alt_tower__ <br>
new_input = (1,1,3,2)

input = [(3,1,3,2), (2,2,3,1), (1,1,3,2)] <br>
indicator_dict = {(3,1,3,2): [1,1], (2,1,2,3): [1,1], (2,2,3,1): [1,0], (1,2,1,3): [1,1], (1,1,3,2): [0,0]}

__since indicator is not [1,1], we do nothing else__ <br>      

__increment n_ops by 1 as we reached the end__ <br>
n_ops = 7

---------------------------------------------------------------------------

__iteration 8:__

__take the last value in input list as initial argument__ <br>   
n, source, target, aux = (1,1,3,2)

n_ops == 7 and the next input is not the root so we move on.

since n = 1, we do not enter the first loop.

__input is not the root and its indicators are not [1,1] so we print__

print('Move disk 1 from 1 to 3.')

__now we activate the left key.__ <br>
indicator_dict = {(3,1,3,2): [1,1], (2,1,2,3): [1,1], (2,2,3,1): [1,0], (1,2,1,3): [1,1], (1,1,3,2): [1,0]}

__n is not greater than 1 so we move on.__ <br>

__now we activate the right key.__ <br>
indicator_dict = {(3,1,3,2): [1,1], (2,1,2,3): [1,1], (2,2,3,1): [1,0], (1,2,1,3): [1,1], (1,1,3,2): [1,1]}

__since indicator is [1,1], we delete the input__ <br>
input = [(3,1,3,2), (2,2,3,1)]
      
__(2,2,3,1) has indicators [1,0] and so we turn it to [1,1] as we have passed both sides of (2,2,3,1). However, (3,1,3,2) is not [1,0] and so we stop__.<br>
indicator_dict = {(3,1,3,2): [1,1], (2,1,2,3): [1,1], (2,2,3,1): [1,1], (1,2,1,3): [1,1], (1,1,3,2): [1,1]}     

__increment n_ops by 1 as we reached the end__ <br>
n_ops = 8

------------------------------------------------------------------------

__iteration 9:__

__take the last value in input list as initial argument__ <br>   
n, source, target, aux = (2,2,3,1)

n_ops == 8 and the next input is not the root so we move on.

since n is greater than 1 we enter the first loop.

__we swop to_tower and alt_tower__ <br>
new_input = (1,2,3,1)

__new_input is in indicator_dict and both indicators of current input are not 0, and so we break out of this loop as we have already passed through the left of (2,2,3,1)__

__input is not the root but the indicators are [1,1] so we do not print__

__the left indicator is already 1.__ <br>

__n is greater than 1 and so we enter the right side__<br>

__we now swop from_tower and alt_tower__ <br>
new_input = (1,1,3,2)

__new_input is in indicator_dict and the right indicator of current input is not 0 and so we move on.__

__right indicator is already 1.__

__since indicator is [1,1], we delete the input__ <br>
input = [(3,1,3,2)]

__(3,1,3,2) is already [1,1] and so move on.__      

__increment n_ops by 1 as we reached the end__ <br>
n_ops = 9

------------------------------------------------------------------------

__iteration 10:__

__take the last value in input list as initial argument__ <br>   
n, source, target, aux = (3,1,3,2)

n_ops == 10 and the next input is the root so we remove all branches below N - 1.

indicator_dict = {(3,1,3,2): [1,1], (2,1,2,3): [1,1], (2,2,3,1): [1,1]}    

since n is greater than 1 we enter the first loop.

__we swop to_tower and alt_tower__ <br>
new_input = (2,1,2,3)

__new_input is in indicator_dict and both indicators of current input are not 0, and so we break out of this loop as we have already passed through the left of (2,1,2,3)__

__input is not the root but the indicators are [1,1] so we do not print__

__the left indicator is already 1.__ <br>

__n is greater than 1 and so we enter the right side__<br>

__we now swop from_tower and alt_tower__ <br>
new_input = (2,2,3,1)

__new_input is in indicator_dict and the right indicator of current input is not 0 and so we move on.__

__right indicator is already 1.__

__since indicator is [1,1], we delete the input__ <br>
input = []

__input is empty and so we move on.__      

__increment n_ops by 1 as we reached the end__ <br>
n_ops = 10

__This is the end of the program as now input is empty.__

13. Draw the recursion tree for my_quicksort([5,4,6,2,9,1,7,3]).

In [68]:
# recursive function from the textbook
# link: https://pythonnumericalmethods.berkeley.edu/notebooks/chapter06.02-Divide-and-Conquer.html
def my_quicksort(lst):
    
    if len(lst) <= 1:
        # list of length 1 is easiest to sort 
        # because it is already sorted
        
        sorted_list = lst    
    else:
        
        # select pivot as teh first element of the list
        pivot = lst[0]
        
        # initialize lists for bigger and smaller elements 
        # as well those equal to the pivot
        bigger = []
        smaller = []
        same = []
        
        # loop through list and put elements into appropriate array
        
        for item in lst:
            if item > pivot:
                bigger.append(item)
            elif item < pivot:
                smaller.append(item)
            else:
                same.append(item)
        
        sorted_list = my_quicksort(smaller) + same + my_quicksort(bigger)
        
    return sorted_list

In [69]:
my_quicksort([5,4,6,2,9,1,7,3])

[1, 2, 3, 4, 5, 6, 7, 9]

__explaining the recursion__

lst: [5,4,6,2,9,1,7,3]

len(lst) > 1 so we move on.

__iteration 1__

pivot = 5

bigger = [] <br>
smaller = [] <br>
same = []

now we enter the for loop using each value in the list.

5 = 5 <br>
same.append(5) <br>
same = [5]

4 < 5 <br>
smaller.append(4) <br>
smaller = [4]

6 > 5 <br>
bigger.append(6) <br>
bigger = [6]

2 < 5 <br>
smaller.append(2) <br>
smaller = [4,2]

9 > 5 <br>
bigger.append(9) <br>
bigger = [6,9]

1 < 5 <br>
smaller.append(1) <br>
smaller = [4,2,1]

7 > 5 <br>
bigger.append(7) <br>
bigger = [6,9,7]

3 < 5 <br>
smaller.append(3) <br>
smaller = [4,2,1,3]

sorted_list = my_quicksort([4,2,1,3]) + [5] + my_quicksort([6,9,7])

now we first wait for the output of my_quicksort([4,2,1,3]) - (i)

--------------------------------------------------------------------------

__iteration 2__

lst: my_quicksort([4,2,1,3])

len(lst) > 1 and so we move on

pivot = 4

bigger = [] <br>
smaller = [] <br>
same = []

now we enter the for loop using each value in the list.

4 = 4 <br>
same.append(4) <br>
same = [4]

2 < 4 <br>
smaller.append(2) <br>
smaller = [2]

1 < 4 <br>
smaller.append(1) <br>
smaller = [2,1]

3 < 4 <br>
smaller.append(3) <br>
smaller = [2,1,3]

sorted_list = my_quicksort([2,1,3]) + [4] + my_quicksort([]) - (ii)

we now wait for my_quicksort([2,1,3])

---------------------------------------------------------------------------

__iteration 3__

lst: my_quicksort([2,1,3])

len(lst) > 1 and so we move on

pivot = 2

bigger = [] <br>
smaller = [] <br>
same = []

now we enter the for loop using each value in the list.

2 = 2 <br>
same.append(2) <br>
same = [2]

1 < 2 <br>
smaller.append(1) <br>
smaller = [1]

3 > 2 <br>
bigger.append(3) <br>
bigger = [3]

sorted_list = my_quicksort([1]) + [2] + my_quicksort([3]) - (iii)

we now wait for my_quicksort([1])

---------------------------------------------------------------------------

__iteration 4__

lst: my_quicksort([1])

len(lst) = 1 and thus we have reached the base case and we return the list as is.

substituting this in (iii)

sorted_list = my_quicksort([1]) + [2] + my_quicksort([3]) <br>
sorted_list = [1] + [2] + my_quicksort([3]) - (iv)

we now wait for my_quicksort([3])

---------------------------------------------------------------------------

__iteration 5__

lst: my_quicksort([3])

len(lst) = 1 and thus we we return the list as is.

substituting this in (iv)

sorted_list = [1] + [2] + [3] <br>
sorted_list = [1,2,3]

substituting this in (ii) we get

sorted_list = my_quicksort([2,1,3]) + [4] + my_quicksort([]) <br>
sorted_list = [1,2,3] + [4] + my_quicksort([]) - (v)

we now wait for my_quicksort([])

---------------------------------------------------------------------------

__iteration 6__

lst: my_quicksort([])

len(lst) < 1 and thus we we return the list as is.

substituting this in (v)

sorted_list = [1,2,3] + [4] + my_quicksort([]) <br>
sorted_list = [1,2,3] + [4] + [] <br>
sorted_list = [1,2,3,4]

substituting this in (i) we get

sorted_list = my_quicksort([2,1,3]) + [4] + my_quicksort([]) <br>
sorted_list = [1,2,3] + [4] + my_quicksort([])

sorted_list = my_quicksort([4,2,1,3]) + [5] + my_quicksort([6,9,7]) <br>
sorted_list = [1,2,3,4] + [5] + my_quicksort([6,9,7]) - (vi)

we now wait for my_quicksort([6,9,7])

---------------------------------------------------------------------------

__iteration 7__

lst: my_quicksort([6,9,7])

len(lst) > 1 and so we move on

pivot = 6

bigger = [] <br>
smaller = [] <br>
same = []

now we enter the for loop using each value in the list.

6 = 6 <br>
same.append(6) <br>
same = [6]

9 > 6 <br>
bigger.append(9) <br>
bigger = [9]

7 > 6 <br>
bigger.append(7) <br>
bigger = [9,7]

sorted_list = my_quicksort([]) + [6] + my_quicksort([9,7]) - (vii)

we now wait for my_quicksort([])

---------------------------------------------------------------------------

__iteration 8__

lst: my_quicksort([])

len(lst) < 1 and so we return lst as is.

substituting this in (vii)

sorted_list = [] + [6] + my_quicksort([9,7]) - (vii)

we now wait for my_quicksort([9,7])

---------------------------------------------------------------------------

__iteration 9__

lst: my_quicksort([9,7])

len(lst) > 1 and so we move on

pivot = 9

bigger = [] <br>
smaller = [] <br>
same = []

now we enter the for loop using each value in the list.

9 = 9 <br>
same.append(9) <br>
same = [9]

7 < 9 <br>
smaller.append(7) <br>
smaller = [7]

sorted_list = my_quicksort([7]) + [9] + my_quicksort([]) - (viii)

we now wait for my_quicksort([7])

---------------------------------------------------------------------------

__iteration 10__

lst: my_quicksort([7])

len(lst) = 1 and thus we we return the list as is.

substituting this in (viii)

sorted_list = my_quicksort([7]) + [9] + my_quicksort([]) <br>
sorted_list = [7] + [9] + my_quicksort([]) - (ix)

we now wait for my_quicksort([])

---------------------------------------------------------------------------

__iteration 11__

lst: my_quicksort([])

len(lst) < 1 and thus we we return the list as is.

substituting this in (ix)

sorted_list = [7] + [9] + my_quicksort([]) <br>
sorted_list = [7] + [9] + [] <br>
sorted_list = [7,9]

substituting this in (vii)

sorted_list = [] + [6] + my_quicksort([9,7]) <br>
sorted_list = [] + [6] + [7,9] <br>
sorted_list = [6,7,9]

substituting this in vi

sorted_list = [1,2,3,4] + [5] + my_quicksort([6,9,7]) <br>
sorted_list = [1,2,3,4] + [5] + [6,7,9] <br>
sorted_list = [1,2,3,4,5,6,7,9]

end of program

--------------------------------------------------------------------------

__Recursion tree of quicksort__


<pre>
                                      (0)
                                [5,4,6,2,9,1,7,3]
                 (1)                                       (4)
              [4,2,1,3]               [5]                [6,9,7]

         (2)                                           (5)        
       [2,1,3]  + [4]  + []                       [] + [6] + [9,7]

     (3)                                                          (6)
[1]  [2]  [3]                                               [7] + [9] + []
               
</pre>

 (3): [1] + [2] + [3] = [1,2,3] <br>
      [1,2,3] + [4] + [] = [1,2,3,4] <br>
      [1,2,3,4] + [5] = [1,2,3,4,5] <br>  
 (6): [7] + [9] + [] = [7,9] <br>
      [] + [6] + [7,9] = [6,7,9] <br>
      [1,2,3,4,5] + [6,7,9] = [1,2,3,4,5,6,7,9] 

14. Rewrite the quicksort function in this chapter without using recursion.

In [70]:
# The solution has been provided by Chat GPT. We will work on breaking it down

def quicksort_iter(arr):
    if len(arr) <= 1:
        return arr

    # Create a stack to simulate recursion
    stack = []
    stack.append((0, len(arr) - 1))

    while stack:
        # Pop the left and right indices from the top of the stack
        left, right = stack.pop()

        # Partition the array
        pivot = arr[right]
        i = left - 1
        for j in range(left, right):
            if arr[j] <= pivot:
                i += 1
                arr[i], arr[j] = arr[j], arr[i]
        arr[i + 1], arr[right] = arr[right], arr[i + 1]

        # Add new subarrays to the stack
        if i - left > 0:
            stack.append((left, i))
        if right - i > 1:
            stack.append((i + 1, right))

    return arr


In [71]:
quicksort_iter([5,4,6,2,9,1,7,3])

[1, 2, 3, 4, 5, 6, 7, 9]

In [72]:
quicksort_iter([5,10,4,6,2,9,1,7,3,17,13,8])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 13, 17]

In [73]:
quicksort_iter([5,10,4,6,5,2,2,9,1,7,3,17,13,8])

[1, 2, 2, 3, 4, 5, 5, 6, 7, 8, 9, 10, 13, 17]

Breaking down the ChatGPT solution:

arr: [5,4,6,2,9,1,7,3]

len(arr) > 1

stack.append((0,7)) <br>
stack = [(0,7)]

now we enter the while loop

__iteration 1:__

__extract the last value from stack.__ <br>
left, right = stack.pop() = (0,7) <br>
stack = []

__arr[right]__ <br>
pivot = arr[7] = 3

__i = left - 1__ <br>
i = 0 - 1 = -1

__loop over the array from 0 to 6 with iterable j (upper bound is excluded)__

__if arr[j] <= pivot then i += 1 and swap arr[i] and arr[j] else move on.__

arr[j] = arr[0] = 5 <br>
5 > 3 so we move on

arr[j] = arr[1] = 4 <br>
4 > 3 so we move on

arr[j] = arr[2] = 6 <br>
6 > 3 so we move on

arr[j] = arr[3] = 2 <br>
2 < 3

i += 1 <br>
i = 0

arr[0], arr[3] = arr[3], arr[0] <br>
arr = [2,4,6,5,9,1,7,3]

arr[j] = arr[4] = 9 <br>
9 > 3 so we move on

arr[j] = arr[5] = 1 <br>
1 < 3 

i += 1 <br>
i = 1

arr[1], arr[5] = arr[5], arr[1] <br>
arr = [2,1,6,5,9,4,7,3]

arr[j] = arr[6] = 7 <br>
7 > 3 so we move on

__we sorted till i = 1, so we swop the next element with the rightmost one__ <br>
arr[1 + 1], arr[7] = arr[7], arr[1 + 1] <br>
arr[2], arr[7] = arr[7], arr[2] <br>
arr = [2,1,3,5,9,4,7,6]

__add new_subarrays to the stack__

__if i - left > 0 then append (left, i) to the stack else move on. If right - i > 1 then append (i+1, right) to the stack else move on.__

i - left = 1 - 0 = 1 <br>
i - left > 0

stack.append((0,1)) <br>
stack = [(0,1)]

right - i = 7 - 1 = 6 <br>
right - i > 1 <br>
i + 1 = 2

stack.append((2,7)) <br>
stack = [(0,1), (2,7)]

---------------------------------------------------------------------------

__iteration 2:__

arr = [2,1,3,5,9,4,7,6]

left, right = stack.pop() = (2,7) <br>
stack = [(0,1)]

pivot = arr[7] = 6

i = 2 - 1 = 1

loop over the array from 2 to 6 with iterable j

arr[j] = arr[2] = 3 <br>
3 < 6 

i += 1 <br>
i = 2

arr[2], arr[2] = arr[2], arr[2] <br>
arr = [2,1,3,5,9,4,7,6]

arr[j] = arr[3] = 5 <br>
5 < 6 so we move on

i += 1 <br>
i = 3

arr[3], arr[3] = arr[3], arr[3] <br>
arr = [2,1,3,5,9,4,7,6]

arr[j] = arr[4] = 9 <br>
9 > 6 so we move on

arr[j] = arr[5] = 4 <br>
4 < 6

i += 1 <br>
i = 4

arr[4], arr[5] = arr[5], arr[4] <br>
arr = [2,1,3,5,4,9,7,6]


arr[j] = arr[6] = 7 <br>
7 > 6 so we move on


__we sorted till i = 4, so we swop the next element with the rightmost one__ <br>
arr[4 + 1], arr[7] = arr[7], arr[4 + 1] <br>
arr[5], arr[7] = arr[7], arr[5] <br>
arr = [2,1,3,5,4,6,7,9]

__add new_subarrays to the stack__

i - left = 4 - 2 = 2 <br>
i - left > 0

stack.append((2,4)) <br>
stack = [(0,1), (2,4)]

right - i = 7 - 4 = 3 <br>
right - i > 1 <br>
i + 1 = 5

stack.append((5,7)) <br>
stack = [(0,1), (2,4), (5,7)]

--------------------------------------------------------------------------

__iteration 3:__

arr = [2,1,3,5,4,6,7,9]

left, right = stack.pop() = (5,7) <br>
stack = [(0,1), (2,4)]

pivot = arr[7] = 9

i = 5 - 1 = 4

loop over the array from 5 to 6 with iterable j

arr[j] = arr[5] = 6 <br>
6 < 9 

i += 1 <br>
i = 5

arr[5], arr[5] = arr[5], arr[5] <br>
arr = [2,1,3,5,4,6,7,9]

arr[j] = arr[6] = 7 <br>
7 < 9 so we move on

i += 1 <br>
i = 6

arr[6], arr[6] = arr[6], arr[6] <br>
arr = [2,1,3,5,4,6,7,9]

__we sorted till i = 6, so we swop the next element with the rightmost one__ <br>
arr[6 + 1], arr[7] = arr[7], arr[6 + 1] <br>
arr[7], arr[7] = arr[7], arr[7] <br>
arr = [2,1,3,5,4,6,7,9]

__add new_subarrays to the stack__

i - left = 6 - 5 = 1 <br>
i - left > 0

stack.append((5,6)) <br>
stack = [(0,1), (2,4), (5,6)]

right - i = 7 - 6 = 1 <br>
right - i = 1 <br>

Thus, we move on and do not add to the stack.

--------------------------------------------------------------------------

__iteration 4:__

arr = [2,1,3,5,4,6,7,9]

left, right = stack.pop() = (5,6) <br>
stack = [(0,1), (2,4)]

pivot = arr[6] = 7

i = 5 - 1 = 4

loop over the array with just 5 with iterable j

arr[j] = arr[5] = 6 <br>
6 < 7 

i += 1 <br>
i = 5

arr[5], arr[5] = arr[5], arr[5] <br>
arr = [2,1,3,5,4,6,7,9]

__we sorted till i = 5, so we swop the next element with the rightmost one__ <br>
arr[5 + 1], arr[6] = arr[6], arr[5 + 1] <br>
arr[6], arr[6] = arr[6], arr[6] <br>
arr = [2,1,3,5,4,6,7,9]

__add new_subarrays to the stack__

i - left = 5 - 5 = 0 <br>
i - left = 0

right - i = 6 - 5 = 1 <br>
right - i = 1 <br>

Thus, we move on and do not add either to the stack.

---------------------------------------------------------------------------

__iteration 5:__

arr = [2,1,3,5,4,6,7,9]

left, right = stack.pop() = (2,4) <br>
stack = [(0,1)]

pivot = arr[4] = 4

i = 2 - 1 = 1

loop over the array from 2 to 3 with iterable j

arr[j] = arr[2] = 3 <br>
3 < 4 

i += 1 <br>
i = 2

arr[2], arr[2] = arr[2], arr[2] <br>
arr = [2,1,3,5,4,6,7,9]

arr[j] = arr[3] = 5 <br>
5 > 4 so we move on 

__we sorted till i = 2, so we swop the next element with the rightmost one__ <br>
arr[2 + 1], arr[4] = arr[4], arr[2 + 1] <br>
arr[3], arr[4] = arr[4], arr[3] <br>
arr = [2,1,3,4,5,6,7,9]

__add new_subarrays to the stack__

i - left = 2 - 2 = 0 <br>
i - left = 0

right - i = 4 - 2 = 2 <br>
right - i > 1 <br>

stack.append((3,4)) <br>
stack = [(0,1), (3,4)]

--------------------------------------------------------------------------

__iteration 6:__

arr = [2,1,3,4,5,6,7,9]

left, right = stack.pop() = (3,4) <br>
stack = [(0,1)]

pivot = arr[4] = 5

i = 3 - 1 = 2

loop over the array using just 3 with iterable j

arr[j] = arr[3] = 4 <br>
4 < 5

i += 1 <br>
i = 3

arr[3], arr[3] = arr[3], arr[3] <br>
arr = [2,1,3,4,5,6,7,9]

__we sorted till i = 3, so we swop the next element with the rightmost one__ <br>
arr[3 + 1], arr[4] = arr[4], arr[3 + 1] <br>
arr[4], arr[4] = arr[4], arr[4] <br>
arr = [2,1,3,4,5,6,7,9]

__add new_subarrays to the stack__

i - left = 3 - 3 = 0 <br>
i - left = 0

right - i = 4 - 3 = 1 <br>
right - i = 1 <br>

Thus, we do not add any more to the stack and move on.

--------------------------------------------------------------------------

__iteration 7:__

arr = [2,1,3,4,5,6,7,9]

left, right = stack.pop() = (0,1) <br>
stack = []

pivot = arr[1] = 1

i = 0 - 1 = -1

loop over the array using just 0 with iterable j

arr[j] = arr[0] = 2 <br>
2 > 1 so we move on

__we sorted till i = -1, so we swop the next element with the rightmost one__ <br>
arr[-1 + 1], arr[1] = arr[1], arr[-1 + 1] <br>
arr[0], arr[1] = arr[1], arr[0] <br>
arr = [1,2,3,4,5,6,7,9]

__add new_subarrays to the stack__

i - left = -1 - 0 = -1 <br>
i - left < 0

right - i = 1 - (-1) = 2 <br>
right - i > 1 <br>

stack.append((0,1))
stack = [(0,1)]

--------------------------------------------------------------------------

__iteration 8:__

arr = [1,2,3,4,5,6,7,9]

left, right = stack.pop() = (0,1) <br>
stack = []

pivot = arr[1] = 2

i = 0 - 1 = -1

loop over the array using just 0 with iterable j

arr[j] = arr[0] = 1 <br>
1 < 2 

i += 1 <br>
i = 0

arr[0], arr[0] = arr[0], arr[0] <br>
arr = [1,2,3,4,5,6,7,9]

__we sorted till i = 0, so we swop the next element with the rightmost one__ <br>
arr[0 + 1], arr[1] = arr[1], arr[0 + 1] <br>
arr[1], arr[1] = arr[1], arr[1] <br>
arr = [1,2,3,4,5,6,7,9]

__add new_subarrays to the stack__

i - left = 0 - 0 = 0 <br>
i - left = 0

1 - 0 = 1 - 0 = 1 <br>
right - i = 1 <br>

Thus, we do not add any more solutions to the stack.

---------------------------------------------------------------------------

Now, the stack is empty so we return arr.

arr = [1,2,3,4,5,6,7,9]

---

### Additional problems on recursion

### Determinants using recursion

A sample example of how determinants are computed.

A = $\begin{bmatrix}1 & 2 & 4\\2 & -1 & 3\\0 & 5 & 1\end{bmatrix}$

det(A) = 1$\begin{bmatrix}-1 & 3\\5 & 1\end{bmatrix}$ - 2$\begin{bmatrix}2 & 3\\0 & 1\end{bmatrix}$ + 4$\begin{bmatrix}2 & -1\\0 & 5\end{bmatrix}$

= 1[-1 * 1 - 3 * 5] - 2[2 * 1 - 3 * 0] + 4[2 * 5 - (-1) * 0] <br>
= 1[-1 - 15] - 2[2 - 0] + 4[10 - 0] <br>
= 1[-16] - 2[2] + 4[10] <br>
= -16 - 4 + 40 <br>
= 20


-------------------------------------------------------------------------

A = $\begin{bmatrix}3 & 5 & 3\\2 & 2 & 5\\3 & 8 & 9\end{bmatrix}$

det(A) = 3$\begin{bmatrix}2 & 5\\8 & 9\end{bmatrix}$ - 5$\begin{bmatrix}2 & 5\\3 & 9\end{bmatrix}$ + 3$\begin{bmatrix}2 & 2\\3 & 8\end{bmatrix}$

= 3[2 * 9 - 5 * 8] - 5[2 * 9 - 5 * 3] + 3[2 * 8 - 2 * 3] <br>
= 3[18 - 40] - 5[18 - 15] + 3[16 - 6] <br>
= 3[-22] - 5[3] + 3[10] <br>
= -66 - 15 + 30 <br>
= -51


In [74]:
# calculates the determinant of a 2 by 2 matrix
def det2D(mat):
  return mat[0,0]*mat[1,1] - mat[0,1]*mat[1,0] 

# the concept of determinants requires extracting different 2 by 2 matrices. This function uses the idx argument to 
# extract 2 by 2 matrices
def smaller_matrix(X, idx):
  # all values are True initially
  bool_matrix = np.ones(X.shape, dtype = bool)
  
  # first row will be false as we will be extracting matrices from row 2 onwards
  bool_matrix[0,:] = False

  # idx here means the column that will be set to false. So, for example we have a 3 by 3 matrix and we wish to extract
  # a 2 by 2 matrix by extracting two rows from column 1 and two rows from column 3, then idx will be 2 to set column 2 
  # as False
  bool_matrix[:,idx] = False

  # once extracted. Reshape them to len(X) - 1, len(X) - 1 so that the output is a matrix
  return X[bool_matrix].reshape(len(X)-1,len(X)-1)

def determinant(X):

  # base case: if its a 2 by 2 matrix then we compute the simple determinant using the formula above
  if len(X) == 2:
    return det2D(X)

  else:
    det = 0
    sign = -1 # first operation is positive followed by negative followed by positive and so on

    # each value in row 1 will be multiplied by a 2 by 2 matrix that contain values from rows below 
    # belonging to other two columns
    for col in range(X.shape[1]):
        sign *= -1 # keep flipping the sign
        det += ( X[0, col] * determinant(smaller_matrix(X, col)) )*sign
    
    return det

In [75]:
import numpy as np

In [76]:
A = np.array([[1,2,4], [2,-1,3], [0,5,1]])
A

array([[ 1,  2,  4],
       [ 2, -1,  3],
       [ 0,  5,  1]])

In [77]:
determinant(A)

20

In [78]:
# verifying with numpy
np.linalg.det(A)

19.999999999999996

In [79]:
A = np.array([[3,5,3], [2,2,5], [3,8,9]])
A

array([[3, 5, 3],
       [2, 2, 5],
       [3, 8, 9]])

In [80]:
determinant(A)

-51

In [81]:
np.linalg.det(A)

-51.00000000000002

__explaining the recursion__

input: A = $\begin{bmatrix}1 & 2 & 4\\2 & -1 & 3\\0 & 5 & 1\end{bmatrix}$

len(A) > 2

det = 0 <br>
sign = -1

__we loop over columns of A, which in this case is 3.__

__flipping the sign:__ <br>
sign *= -1 <br>
sign = 1

col = 0 <br>
det = det + A[0, 0] * determinant(smaller_matrix(A, 0)) ) * sign

det = 0 + 1 * determinant(smaller_matrix(A, 0)) * 1

now we wait for determinant(smaller_matrix(A, 0))

smaller_matrix(A, 0) =  $\begin{bmatrix}-1 & 3\\5 & 1\end{bmatrix}$

determinant(smaller_matrix(A, 0)) = -16

__det = 1 * -16 * 1 = -16__

---------------------------------------------------------------------------

sign *= -1 <br>
sign = -1

col = 1 <br>
det = det + A[0, 1] * determinant(smaller_matrix(A, 1)) ) * sign

det = -16 + 2 * determinant(smaller_matrix(A, 1)) * -1

now we wait for determinant(smaller_matrix(A, 1))

smaller_matrix(A, 1) =  $\begin{bmatrix}2 & 3\\0 & 1\end{bmatrix}$

determinant(smaller_matrix(A, 0)) = 2

det = -16 + 2 * 2 * -1 = -20

---------------------------------------------------------------------------

sign *= -1 <br>
sign = 1

col = 2 <br>
det = det + A[0, 2] * determinant(smaller_matrix(A, 2)) ) * sign

det = -20 + 4 * determinant(smaller_matrix(A, 2)) * 1

now we wait for determinant(smaller_matrix(A, 2))

smaller_matrix(A, 2) =  $\begin{bmatrix}2 & -1\\0 & 5\end{bmatrix}$

determinant(smaller_matrix(A, 2)) = 10

det = -20 + 4 * 10 * 1 = 20

__final answer: 20__


---

Given a number in Roman numeral format, convert it to decimal.

The values of Roman numerals are as follows:

<pre>
{
    'M': 1000,
    'D': 500,
    'C': 100,
    'L': 50,
    'X': 10,
    'V': 5,
    'I': 1
}
</pre>

In addition, note that the Roman numeral system uses subtractive notation for numbers such as IV and XL.

For the input XIV, for instance, you should return 14.

In [82]:
# recursive solution for the problem

PAIRS = {
    'CM': 900,
    'CD': 400,
    'XC': 90,
    'XL': 40,
    'IX': 9,
    'IV': 4
}

SINGLES = {
    'M': 1000,
    'D': 500,
    'C': 100,
    'L': 50,
    'X': 10,
    'V': 5,
    'I': 1
}

def decimate(s, total=0):
    if not s:
        return total
    if s[:2] in PAIRS:
        total += PAIRS[s[:2]]
        return decimate(s[2:], total)
    else:
        total += SINGLES[s[:1]]
        return decimate(s[1:], total)

In [83]:
decimate('XIV')

14

In [84]:
decimate('DCCCXLI')

841

__explaining the recursion:__


s: XIV <br>
total = 0

s is not an empty string so we move on

s[:2] = 'XI'

s[:2] is not in pairs as XI is not a pair for roman numbers and so we move to the eles block.

SINGLES[s[:1]] = SINGLES['X'] = 10

total = total + 10 <br>
total = 0 + 10 = 10

decimate(s[1:], total)

decimate('IV', 10)

---------------------------------------------------------------------------

s: 'IV' <br>
total = 10

s is not an empty string so we move on.

s[:2] is in pairs.

PAIRS[s[:2]] = SINGLES['IV'] = 4

total = total + 4 <br>
total = 10 + 4 = 14

decimate(s[2:], 14) <br>
decimate('', 14)

---------------------------------------------------------------------------

s: '' <br>
total = 14

s is an empty string and so we return the total

__total = 14__