These are the exercise problems from the book Python programming and Numerical methods book:

https://pythonnumericalmethods.berkeley.edu/notebooks/Index.html

# Chapter 15: EIGENVALUES AND EIGENVECTORS

https://pythonnumericalmethods.berkeley.edu/notebooks/chapter15.05-Summary-and-Problems.html#problems

Only those problems that need to be solved in a notebook environment

---

1. Write down the characteristic equation for matrix A = $\begin{bmatrix}3 & 2\\5 & 3\end{bmatrix}$

det(A - λI) = 0

det($\begin{bmatrix}3-λ & 2\\5 & 3-λ\end{bmatrix}$) = 0

$(3 - λ)(3 - λ) - 2*5 = 0$

$(3 - λ)^2 - 10 = 0$

$[9 - 6λ + λ^2] - 10 = 0$

$λ^2 - 6λ + 9 - 10 = 0$

$λ^2 - 6λ - 1 = 0$

--------------------------------------------------------------------

alternate way:

for a 2 by 2 matrix characteristic equation can be written as: <br>
λ^2 - trace(A)λ + det(A) = 0

trace(A) = sum of diagonal elements

trace(A) = 3 + 3 = 6

det(A) = 3 * 3 - 2 * 5 = 9 - 10 = -1

$λ^2 - 6λ - 1 = 0$

---

2. Using the above characteristic equation to solve for eigenvalues and eigenvectors for matrix A.

$λ^2 - 6λ - 1 = 0$

we must use the roots of a quadratic equation formula to solve this:

λ = $\frac{-b ± \sqrt{b^2 - 4ac}}{2a}$

a = 1, b = -6, c = -1

λ = $\frac{-(-6) ± \sqrt{(-6)^2 - 4(1)(-1)}}{2(1)}$

λ = $\frac{6 ± \sqrt{36 + 4}}{2}$

λ = $\frac{6 ± \sqrt{40}}{2}$

λ = [$\frac{6 + \sqrt{40}}{2}, \frac{6 - \sqrt{40}}{2}$]

λ = [6.162278, -0.16227766]


----------------------------------------------------------------------

eigenvectors

eigenvectors would be the vectors that are in the null space of A - λI.

__note:__ Because A - λI is singular, there are many solutions to this problem.


At eigenvalue 6.162278, eigenvector is:

$\begin{bmatrix}3-6.162278 & 2\\5 & 3-6.162278\end{bmatrix}$

<br>

$\begin{bmatrix}-3.162278 & 2\\5 & -3.162278\end{bmatrix}$$\begin{bmatrix}v1\\v2\end{bmatrix}$ = $\begin{bmatrix}0\\0\end{bmatrix}$

Any v1 and v2 that can solve this are our potential eigenvectors for eigenvalue. One simple answer could be:


v = $\begin{bmatrix}1\\1.581139\end{bmatrix}$

note: col 1 in A - λI can be created as a linear combination of col 2.

So, if we divide -3.162278/2, we get -1.581139.

if we take positive 1 and positive 1.581139 then we get:

-3.162278(1) + 2(1.581139) = 0

Any v1 and v2 with a similar relationship can be the eigenvector. We can use a similar process with the other eigenvalue. We'll use numpy to get the eigenvectors.


In [1]:
import numpy as np
import sympy as sym

In [2]:
print((6 + np.sqrt(40))/2)
print((6 - np.sqrt(40))/2)

6.16227766016838
-0.16227766016837952


In [3]:
A = np.array([[3, 2], [5, 3]])
np.linalg.eigvals(A)

array([ 6.16227766, -0.16227766])

In [4]:
np.linalg.eig(A)[1]

array([[ 0.53452248, -0.53452248],
       [ 0.84515425,  0.84515425]])

In [5]:
# np.diag(np.linalg.eigvals(A))
np.linalg.eigvals(A)[0]*np.eye(2)

array([[6.16227766, 0.        ],
       [0.        , 6.16227766]])

verifying if (A - λI)v = [0,0]

In [6]:
A_lambI = A - np.linalg.eigvals(A)[0]*np.eye(2)
A_lambI

array([[-3.16227766,  2.        ],
       [ 5.        , -3.16227766]])

In [7]:
# eigenvector associated with first eigenvalue
np.linalg.eig(A)[1][:,0]

array([0.53452248, 0.84515425])

In [8]:
np.round(A_lambI @ np.linalg.eig(A)[1][:,0], 3)

array([-0., -0.])

---

3. Using the first eigenvector that derived from problem 2 to verify that Ax = λx.

In [9]:
v1 = np.linalg.eig(A)[1][:,0]
lamb1 = np.linalg.eigvals(A)[0]

# Ax - λx = [0,0]
np.round(A @ v1 - lamb1 * v1, 3)

array([-0.,  0.])

---

4. Get the largest eigenvalue and eigenvector for matrix A = $\begin{bmatrix}2 & 1 & 2\\1 & 3 & 2\\2 & 4 & 1\end{bmatrix}$ using the power method. You can start with initial vector [1, 1, 1], see what you will get after 8 iterations.


By hand:

__iteration 1:__

$\begin{bmatrix}2 & 1 & 2\\1 & 3 & 2\\2 & 4 & 1\end{bmatrix}$$\begin{bmatrix}1\\1\\1\end{bmatrix}$ = $\begin{bmatrix}5\\6\\9\end{bmatrix}$

largest value 9

$\begin{bmatrix}2 & 1 & 2\\1 & 3 & 2\\2 & 4 & 1\end{bmatrix}$$\begin{bmatrix}1\\1\\1\end{bmatrix}$ = 9$\begin{bmatrix}5/9\\6/9\\9/9\end{bmatrix}$

__iteration 2:__

$\begin{bmatrix}2 & 1 & 2\\1 & 3 & 2\\2 & 4 & 1\end{bmatrix}$$\begin{bmatrix}5/9\\6/9\\9/9\end{bmatrix}$ = $\begin{bmatrix}3.778\\4.556\\4.778\end{bmatrix}$

largest value 4.778

$\begin{bmatrix}2 & 1 & 2\\1 & 3 & 2\\2 & 4 & 1\end{bmatrix}$$\begin{bmatrix}5/9\\6/9\\9/9\end{bmatrix}$ = 4.778$\begin{bmatrix}0.791\\0.954\\1\end{bmatrix}$

__iteration 3:__

$\begin{bmatrix}2 & 1 & 2\\1 & 3 & 2\\2 & 4 & 1\end{bmatrix}$$\begin{bmatrix}0.791\\0.954\\1\end{bmatrix}$ = $\begin{bmatrix}4.536\\5.653\\6.398\end{bmatrix}$

largest value 6.398

$\begin{bmatrix}2 & 1 & 2\\1 & 3 & 2\\2 & 4 & 1\end{bmatrix}$$\begin{bmatrix}5/9\\6/9\\9/9\end{bmatrix}$ = 6.398$\begin{bmatrix}0.709\\0.884\\1\end{bmatrix}$

__iteration 4:__

$\begin{bmatrix}2 & 1 & 2\\1 & 3 & 2\\2 & 4 & 1\end{bmatrix}$$\begin{bmatrix}0.709\\0.884\\1\end{bmatrix}$ = $\begin{bmatrix}4.302\\5.361\\5.954\end{bmatrix}$

largest value 5.954

$\begin{bmatrix}2 & 1 & 2\\1 & 3 & 2\\2 & 4 & 1\end{bmatrix}$$\begin{bmatrix}5/9\\6/9\\9/9\end{bmatrix}$ = 5.954$\begin{bmatrix}0.723\\0.900\\1\end{bmatrix}$

__iteration 5:__

$\begin{bmatrix}2 & 1 & 2\\1 & 3 & 2\\2 & 4 & 1\end{bmatrix}$$\begin{bmatrix}0.723\\0.900\\1\end{bmatrix}$ = $\begin{bmatrix}4.346\\5.423\\6.046\end{bmatrix}$

largest value 6.046

$\begin{bmatrix}2 & 1 & 2\\1 & 3 & 2\\2 & 4 & 1\end{bmatrix}$$\begin{bmatrix}5/9\\6/9\\9/9\end{bmatrix}$ = 6.046$\begin{bmatrix}0.719\\0.897\\1\end{bmatrix}$

__iteration 6:__

$\begin{bmatrix}2 & 1 & 2\\1 & 3 & 2\\2 & 4 & 1\end{bmatrix}$$\begin{bmatrix}0.719\\0.897\\1\end{bmatrix}$ = $\begin{bmatrix}4.335\\5.410\\6.026\end{bmatrix}$

largest value 6.026

$\begin{bmatrix}2 & 1 & 2\\1 & 3 & 2\\2 & 4 & 1\end{bmatrix}$$\begin{bmatrix}5/9\\6/9\\9/9\end{bmatrix}$ = 6.026$\begin{bmatrix}0.719\\0.898\\1\end{bmatrix}$

__iteration 7:__

$\begin{bmatrix}2 & 1 & 2\\1 & 3 & 2\\2 & 4 & 1\end{bmatrix}$$\begin{bmatrix}0.719\\0.898\\1\end{bmatrix}$ = $\begin{bmatrix}4.336\\5.413\\6.030\end{bmatrix}$

largest value 6.030

$\begin{bmatrix}2 & 1 & 2\\1 & 3 & 2\\2 & 4 & 1\end{bmatrix}$$\begin{bmatrix}5/9\\6/9\\9/9\end{bmatrix}$ = 6.030$\begin{bmatrix}0.719\\0.898\\1\end{bmatrix}$

__iteration 8:__

$\begin{bmatrix}2 & 1 & 2\\1 & 3 & 2\\2 & 4 & 1\end{bmatrix}$$\begin{bmatrix}0.719\\0.898\\1\end{bmatrix}$ = $\begin{bmatrix}4.336\\5.413\\6.030\end{bmatrix}$

largest value 6.030

$\begin{bmatrix}2 & 1 & 2\\1 & 3 & 2\\2 & 4 & 1\end{bmatrix}$$\begin{bmatrix}5/9\\6/9\\9/9\end{bmatrix}$ = 6.030$\begin{bmatrix}0.719\\0.898\\1\end{bmatrix}$

The results might wary in the program due to rounding errors.

largest eigenvalue = 0.719

eigenvector associated with the largest eigenvalue = $\begin{bmatrix}0.719\\0.898\\1\end{bmatrix}$

Iteration 2 calc

In [10]:
print(2*(5/9) + 1*(6/9) + 2*(9/9))
print(1*(5/9) + 3*(6/9) + 2*(9/9))
print(2*(5/9) + 4*(6/9) + 1*(9/9))

3.7777777777777777
4.555555555555555
4.777777777777778


In [11]:
print(3.778/4.778)
print(4.556/4.778)

0.790707408957723
0.9535370447886146


Iteration 3 calc

In [12]:
print(2*(0.791) + 1*(0.954) + 2*(1))
print(1*(0.791) + 3*(0.954) + 2*(1))
print(2*(0.791) + 4*(0.954) + 1*(1))

4.536
5.6530000000000005
6.398


In [13]:
print(4.536/6.398)
print(5.653/6.398)

0.7089715536105032
0.8835573616755236


Iteration 4 calc

In [14]:
print(2*(0.709) + 1*(0.884) + 2*(1))
print(1*(0.709) + 3*(0.884) + 2*(1))
print(2*(0.709) + 4*(0.884) + 1*(1))

4.302
5.361000000000001
5.954


In [15]:
print(4.302/5.954)
print(5.361/5.954)

0.7225394692643601
0.9004030903594222


Iteration 5 calc

In [16]:
print(2*(0.723) + 1*(0.900) + 2*(1))
print(1*(0.723) + 3*(0.900) + 2*(1))
print(2*(0.723) + 4*(0.900) + 1*(1))

4.346
5.423
6.046


In [17]:
print(4.346/6.046)
print(5.423/6.046)

0.7188223618921601
0.8969566655640092


Iteration 6 calc

In [18]:
print(2*(0.719) + 1*(0.897) + 2*(1))
print(1*(0.719) + 3*(0.897) + 2*(1))
print(2*(0.719) + 4*(0.897) + 1*(1))

4.335
5.41
6.026


In [19]:
print(4.335/6.026)
print(5.41/6.026)

0.7193826750746765
0.8977763026883505


Iteration 7 calc

In [20]:
print(2*(0.719) + 1*(0.898) + 2*(1))
print(1*(0.719) + 3*(0.898) + 2*(1))
print(2*(0.719) + 4*(0.898) + 1*(1))

4.336
5.413
6.03


In [21]:
print(4.336/6.030)
print(5.413/6.030)

0.7190713101160863
0.8976782752902156


Doing the same with code

The formula provided on pg.271 of the textbook is incorrect. you must divide the vector by the highest absolute value to normalize it instead of maximum value.

In [22]:
def normalize_vector(v):

  largest_val = np.abs(v).max()
  v_norm = v/largest_val

  return largest_val, v_norm

In [23]:
normalize_vector(np.array([4.336, 5.413, 6.030]))

(6.03, array([0.71907131, 0.89767828, 1.        ]))

In [24]:
A = np.array([[2,1,2],[1,3,2],[2,4,1]])
A

array([[2, 1, 2],
       [1, 3, 2],
       [2, 4, 1]])

In [25]:
n_iterations = 8
x_new = [1,1,1]

for iter in range(n_iterations):
  x_new = A @ x_new
  largest_eigval, x_new = normalize_vector(x_new)

  print(f'eigenvalue at iteration: {iter+1}')
  print(f'largest eigenvalue: {largest_eigval}')
  print(f'eigenvector: {x_new}')
  print('='*50)

print(f'eigenvalue at iteration: {iter+1}')
print(f'largest eigenvalue (final): {largest_eigval}')
print(f'eigenvector: {x_new}')

eigenvalue at iteration: 1
largest eigenvalue: 7
eigenvector: [0.71428571 0.85714286 1.        ]
eigenvalue at iteration: 2
largest eigenvalue: 5.857142857142857
eigenvector: [0.73170732 0.90243902 1.        ]
eigenvalue at iteration: 3
largest eigenvalue: 6.073170731707317
eigenvector: [0.7188755  0.89558233 1.        ]
eigenvalue at iteration: 4
largest eigenvalue: 6.020080321285141
eigenvector: [0.71981321 0.89793195 1.        ]
eigenvalue at iteration: 5
largest eigenvalue: 6.031354236157438
eigenvector: [0.71916823 0.8975777  1.        ]
eigenvalue at iteration: 6
largest eigenvalue: 6.028647273531689
eigenvector: [0.71921842 0.89769746 1.        ]
eigenvalue at iteration: 7
largest eigenvalue: 6.029226676451701
eigenvector: [0.71918581 0.8976791  1.        ]
eigenvalue at iteration: 8
largest eigenvalue: 6.029088043137578
eigenvector: [0.71918849 0.8976852  1.        ]
eigenvalue at iteration: 8
largest eigenvalue (final): 6.029088043137578
eigenvector: [0.71918849 0.8976852  1. 

verifying the solution with numpy linalg

In [26]:
np.linalg.eigvals(A)[0]

6.029111920025985

In [27]:
# verifying Ax - λx = [0,0,0]
A_lambI = A - largest_eigval*np.eye(3)
np.round(A_lambI @ x_new, 3)

array([0., 0., 0.])

---

For the smallest eigenvalue, we use the inverse of A. An example below goes over it.

Another example with step by step walkthrough:

Reference video: <br>
https://www.youtube.com/watch?v=U_0hHhM06B0

In [28]:
A = np.array([[1,2,3],
              [0,1,4],
              [5,6,0]])

A

array([[1, 2, 3],
       [0, 1, 4],
       [5, 6, 0]])

In [29]:
A_inv = np.linalg.inv(A)
A_inv

array([[-24.,  18.,   5.],
       [ 20., -15.,  -4.],
       [ -5.,   4.,   1.]])

Iteration 1

In [30]:
x_new = [1,1,1]

x_new = A_inv @ x_new
np.round(x_new, 4)

array([-1.,  1., -0.])

In [31]:
normalize_vector(x_new)[0]

1.0000000000000036

In [32]:
np.round(normalize_vector(x_new)[1], 4)

array([-1.,  1., -0.])

In [33]:
smallest_eigval, x_new = normalize_vector(x_new)
print(round(smallest_eigval, 4))
print(np.round(x_new, 4))

1.0
[-1.  1. -0.]


Iteration 2

In [34]:
x_new = A_inv @ x_new
np.round(x_new, 3)

array([ 42., -35.,   9.])

In [35]:
smallest_eigval, x_new = normalize_vector(x_new)
print(round(smallest_eigval, 4))
print(np.round(x_new, 4))

42.0
[ 1.     -0.8333  0.2143]


Iteration 3

In [36]:
x_new = A_inv @ x_new
np.round(x_new, 4)

array([-37.9286,  31.6429,  -8.119 ])

In [37]:
smallest_eigval, x_new = normalize_vector(x_new)
print(round(smallest_eigval,4))
print(np.round(x_new, 4))

37.9286
[-1.      0.8343 -0.2141]


Iteration 4

In [38]:
x_new = A_inv @ x_new
np.round(x_new, 4)

array([ 37.9466, -31.6579,   8.123 ])

In [39]:
smallest_eigval, x_new = normalize_vector(x_new)
print(round(smallest_eigval,4))
print(np.round(x_new, 4))

37.9466
[ 1.     -0.8343  0.2141]


Iteration 5

In [40]:
x_new = A_inv @ x_new
np.round(x_new, 4)

array([-37.9466,  31.6578,  -8.123 ])

In [41]:
smallest_eigval, x_new = normalize_vector(x_new)
print(round(smallest_eigval,4))
print(np.round(x_new, 4))

37.9466
[-1.      0.8343 -0.2141]


In [42]:
smallest_eigval

37.94659961289696

In [43]:
1/smallest_eigval

0.026352822392553158

verifying with np.linalg.eigvals

In [44]:
np.linalg.eigvals(A)

array([-5.2296696 , -0.02635282,  7.25602242])

---

In [45]:
n_iterations = 8
x_new = [1,1,1]

for iter in range(n_iterations):
  x_new = A_inv @ x_new
  smallest_eigval, x_new = normalize_vector(x_new)

  print(f'eigenvalue at iteration: {iter+1}')
  print(f'eigenvalue: {smallest_eigval}')
  print(f'eigenvector: {x_new}')
  print('='*50)

print(f'eigenvalue at iteration: {iter+1}')
print(f'smallest eigenvalue (final): {smallest_eigval}')
print(f'eigenvector: {x_new}')

eigenvalue at iteration: 1
eigenvalue: 1.0000000000000036
eigenvector: [-1.0000000e+00  1.0000000e+00 -8.8817842e-16]
eigenvalue at iteration: 2
eigenvalue: 42.00000000000014
eigenvector: [ 1.         -0.83333333  0.21428571]
eigenvalue at iteration: 3
eigenvalue: 37.928571428571566
eigenvector: [-1.          0.83427495 -0.21406152]
eigenvalue at iteration: 4
eigenvalue: 37.94664155681118
eigenvector: [ 1.         -0.83427352  0.21406475]
eigenvalue at iteration: 5
eigenvalue: 37.94659961289696
eigenvector: [-1.          0.83427354 -0.21406475]
eigenvalue at iteration: 6
eigenvalue: 37.9465998847346
eigenvector: [ 1.         -0.83427354  0.21406475]
eigenvalue at iteration: 7
eigenvalue: 37.94659988434952
eigenvector: [-1.          0.83427354 -0.21406475]
eigenvalue at iteration: 8
eigenvalue: 37.94659988435395
eigenvector: [ 1.         -0.83427354  0.21406475]
eigenvalue at iteration: 8
smallest eigenvalue (final): 37.94659988435395
eigenvector: [ 1.         -0.83427354  0.21406475]


In [46]:
1/smallest_eigval

0.026352822204034083

This one converged very quickly at about 6 iterations.

---

5. Using the inverse power method to get the smallest eigenvalue and eigenvector for the matrix in problem 4. See how many iterations do you need for it to converge to the smallest eigenvalue.

In [47]:
A = np.array([[2,1,2],[1,3,2],[2,4,1]])
A

array([[2, 1, 2],
       [1, 3, 2],
       [2, 4, 1]])

In [48]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.45454545, -0.63636364,  0.36363636],
       [-0.27272727,  0.18181818,  0.18181818],
       [ 0.18181818,  0.54545455, -0.45454545]])

---

In [49]:
n_iterations = 300
x_new = [1,1,1]

for iter in range(n_iterations):
  x_new = A_inv @ x_new
  smallest_eigval, x_new = normalize_vector(x_new)

  if iter % 10 == 0:
    print(f'eigenvalue at iteration: {iter+1}')
    print(f'eigenvalue: {smallest_eigval}')
    print(f'eigenvector: {x_new}')
    print('='*50)

print(f'smallest eigenvalue (final): {smallest_eigval}')
print(f'eigenvector: {x_new}')

eigenvalue at iteration: 1
eigenvalue: 0.2727272727272727
eigenvector: [0.66666667 0.33333333 1.        ]
eigenvalue at iteration: 11
eigenvalue: 0.4182699952648921
eigenvector: [ 0.76749256 -1.          0.92790755]
eigenvalue at iteration: 21
eigenvalue: 0.4125512107069618
eigenvector: [ 0.92947152 -1.          0.78249923]
eigenvalue at iteration: 31
eigenvalue: 0.43944296842306196
eigenvector: [ 1.         -0.92713322  0.60137068]
eigenvalue at iteration: 41
eigenvalue: 0.4888388129660573
eigenvector: [ 1.         -0.82419206  0.43492807]
eigenvalue at iteration: 51
eigenvalue: 0.5317959198084429
eigenvector: [ 1.         -0.75021601  0.3153183 ]
eigenvalue at iteration: 61
eigenvalue: 0.568688665614859
eigenvector: [ 1.         -0.69560399  0.22701769]
eigenvalue at iteration: 71
eigenvalue: 0.6000339311729763
eigenvector: [ 1.         -0.65448065  0.16052653]
eigenvalue at iteration: 81
eigenvalue: 0.6264232211883579
eigenvector: [ 1.         -0.62305018  0.1097075 ]
eigenvalue at 

In [50]:
smallest_eigval

0.7495452667030331

In [51]:
1/smallest_eigval

1.334142238531667

verifying the solution with numpy linalg

In [52]:
np.linalg.eigvals(A)

array([ 6.02911192,  1.33625596, -1.36536788])

We can observe that in the first few itertions the optimal value had very high variation deviating from about 0.40 to 1.26. The optimal value is around 0.748. As we increase the no of iterations we see the value starts revolving around that optimal value. However, even after 300 iterations we are still a little off.

In [53]:
# what the optimum value from inverse power iteration should be (reciprocal of the absolute lowest eigval of A derived from inbuilt)
1/1.33625596

0.7483596181677649

In this case we ran 300 iterations to get to the absolute highest eigenvalue of $A^-1$. There will be matrices like these where convergance woule take a lot of iterations. One way to do it better is to use a tolerance like 0.001 between iterations to see when variation is minimal.

Using tolerance

---

In [54]:
x_new = [1,1,1]
tol = 0.00000001
prev_val = 0
next_val = 0
iter = 1

while True:
  x_new = A_inv @ x_new
  next_val, x_new = normalize_vector(x_new)

  if iter % 50 == 0:
    print(f'eigenvalue at iteration: {iter}')
    print(f'eigenvalue: {next_val}')
    print(f'eigenvector: {x_new}')
    print('='*50)

  if abs(next_val - prev_val) < tol:
    break

  prev_val = next_val
  iter += 1

print(f'Total iterations for convergance: {iter}')
print(f'optimum eigenvalue (final): {next_val}')
print(f'eigenvector: {x_new}')

eigenvalue at iteration: 50
eigenvalue: 1.06254160389295
eigenvector: [ 1.         -0.32971954 -0.36457042]
eigenvalue at iteration: 100
eigenvalue: 0.8421793717826448
eigenvector: [ 1.         -0.43996316 -0.18632067]
eigenvalue at iteration: 150
eigenvalue: 0.7790153902834122
eigenvector: [ 1.         -0.48306399 -0.11663216]
eigenvalue at iteration: 200
eigenvalue: 0.7586544809092398
eigenvector: [ 1.         -0.49848717 -0.09169486]
eigenvalue at iteration: 250
eigenvalue: 0.7518480646370544
eigenvector: [ 1.         -0.50382926 -0.08305739]
eigenvalue at iteration: 300
eigenvalue: 0.7495452667030331
eigenvector: [ 1.         -0.5056586  -0.08009958]
eigenvalue at iteration: 350
eigenvalue: 0.7487630071678574
eigenvector: [ 1.         -0.50628259 -0.07909067]
eigenvalue at iteration: 400
eigenvalue: 0.7484969088091529
eigenvector: [ 1.         -0.50649515 -0.078747  ]
eigenvalue at iteration: 450
eigenvalue: 0.7484063488383206
eigenvector: [ 1.         -0.50656752 -0.07862998]
eige

In [55]:
next_val

0.7483596114527826

In [56]:
1/next_val

1.336255971990138

In [57]:
np.abs(np.linalg.eigvals(A)).min()

1.3362559632125934

In [58]:
# verifying Ax - λx = [0,0,0]
smallest_eigval = (1/next_val)
A_lambI = A - smallest_eigval*np.eye(3)
np.round(A_lambI @ x_new, 6)

array([ 0.,  0., -0.])

We played around with the tolerance and it took an extremely low tolerance of 0.00000001 with 875 iterations to converge. This could be problematic with larger matrices.

---

verifying our results match the textbook example on pg 272.

__note:__ Our results will match the power iteration for the largest eigenvalue but the solution for smallest in the textbook is inaccurate as it uses max(v) to normalize v instead of absolute(max(v)). Our solution is the correct one as we verified it with inbuilt method.

Power

In [59]:
n_iterations = 8
x_new = [1,1]
A = np.array([[0, 2],
              [2, 3]])

for iter in range(n_iterations):
  x_new = A @ x_new
  largest_eigval, x_new = normalize_vector(x_new)

  print(f'eigenvalue at iteration: {iter+1}')
  print(f'largest eigenvalue: {largest_eigval}')
  print(f'eigenvector: {x_new}')
  print('='*50)

print(f'eigenvalue at iteration: {iter+1}')
print(f'largest eigenvalue (final): {largest_eigval}')
print(f'eigenvector: {x_new}')

eigenvalue at iteration: 1
largest eigenvalue: 5
eigenvector: [0.4 1. ]
eigenvalue at iteration: 2
largest eigenvalue: 3.8
eigenvector: [0.52631579 1.        ]
eigenvalue at iteration: 3
largest eigenvalue: 4.052631578947368
eigenvector: [0.49350649 1.        ]
eigenvalue at iteration: 4
largest eigenvalue: 3.987012987012987
eigenvector: [0.50162866 1.        ]
eigenvalue at iteration: 5
largest eigenvalue: 4.0032573289902285
eigenvector: [0.49959317 1.        ]
eigenvalue at iteration: 6
largest eigenvalue: 3.999186330349878
eigenvector: [0.50010173 1.        ]
eigenvalue at iteration: 7
largest eigenvalue: 4.000203458799593
eigenvector: [0.49997457 1.        ]
eigenvalue at iteration: 8
largest eigenvalue: 3.999949137887188
eigenvector: [0.50000636 1.        ]
eigenvalue at iteration: 8
largest eigenvalue (final): 3.999949137887188
eigenvector: [0.50000636 1.        ]


Inverse power

In [60]:
n_iterations = 8
A_inv = np.linalg.inv(A)
x_new = [1,1]

for iter in range(n_iterations):
  x_new = A_inv @ x_new
  smallest_eigval, x_new = normalize_vector(x_new)

  print(f'eigenvalue at iteration: {iter+1}')
  print(f'eigenvalue: {smallest_eigval}')
  print(f'eigenvector: {x_new}')
  print('='*50)

print(f'eigenvalue at iteration: {iter+1}')
print(f'smallest eigenvalue (final): {smallest_eigval}')
print(f'eigenvector: {x_new}')

eigenvalue at iteration: 1
eigenvalue: 0.5
eigenvector: [-0.5  1. ]
eigenvalue at iteration: 2
eigenvalue: 0.875
eigenvector: [ 1.         -0.28571429]
eigenvalue at iteration: 3
eigenvalue: 0.8928571428571428
eigenvector: [-1.    0.56]
eigenvalue at iteration: 4
eigenvalue: 1.03
eigenvector: [ 1.         -0.48543689]
eigenvalue at iteration: 5
eigenvalue: 0.9927184466019418
eigenvector: [-1.          0.50366748]
eigenvalue at iteration: 6
eigenvalue: 1.0018337408312958
eigenvector: [ 1.         -0.49908481]
eigenvalue at iteration: 7
eigenvalue: 0.99954240390482
eigenvector: [-1.         0.5002289]
eigenvalue at iteration: 8
eigenvalue: 1.000114451396307
eigenvector: [ 1.         -0.49994278]
eigenvalue at iteration: 8
smallest eigenvalue (final): 1.000114451396307
eigenvector: [ 1.         -0.49994278]


In [61]:
1/smallest_eigval

0.9998855617013162

In [62]:
np.abs(np.linalg.eigvals(A)).min()

1.0

---

6. Do a QR decomposition for matrix 𝐴
 in problem 4, and verify that 𝐴=𝑄𝑅
 and 𝑄
 is an orthogonal matrix.

In [63]:
A = np.array([[2,1,2],[1,3,2],[2,4,1]])
A

array([[2, 1, 2],
       [1, 3, 2],
       [2, 4, 1]])

In [64]:
# verifying A = QR
Q, R = np.linalg.qr(A)

Q @ R
print(np.array_equal(np.round(A), np.round(Q @ R)))

True


verifying that Q is an Orthonormal matrix

Orthonormal means all columns are orthogonal to each other (dot product = 0) and each column has unit norm (magnitude = 1).

In [65]:
# orthogonal
for i in range(3):
  for j in range(3):
    if j > i:
       print(f'Q[{i}] @ Q[{j}] = {round(np.abs(Q[i] @ Q[j]), 8)}')

print()

# unit norm
for i in range(3):
  print(f'norm of Q[{i}] = {round(np.linalg.norm(Q[i]), 4)}')

Q[0] @ Q[1] = 0.0
Q[0] @ Q[2] = 0.0
Q[1] @ Q[2] = 0.0

norm of Q[0] = 1.0
norm of Q[1] = 1.0
norm of Q[2] = 1.0


---

7. Use the QR method to get all the eigenvalues for matrix 𝐴
 in problem 4.

In [66]:
n_iterations = 800
A_eig = A.copy()

for iter in range(n_iterations):
  Q, R = np.linalg.qr(A_eig)
  A_eig = R @ Q

  if (iter + 1) % 50 == 0:
    print(f'At iteration {iter + 1} matrix is:')
    print(A_eig)
    print('='*50)

print('Final matrix:')
print(A_eig)

At iteration 50 matrix is:
[[ 6.02911192e+00  8.95264315e-01 -1.51917865e+00]
 [ 1.74024844e-32  1.40239528e+00 -2.72881277e-01]
 [ 2.90117065e-32  6.70833747e-01 -1.43150720e+00]]
At iteration 100 matrix is:
[[ 6.02911192e+00  1.48403262e+00 -9.52391268e-01]
 [-2.94764115e-65  6.66217235e-01  7.86669492e-01]
 [ 1.52810544e-64  1.73038452e+00 -6.95329155e-01]]
At iteration 150 matrix is:
[[ 6.02911192e+00 -1.74913347e+00 -2.23459264e-01]
 [ 6.96919559e-97 -1.13484844e+00  4.18247611e-01]
 [-4.44611609e-97  1.36196263e+00  1.10573652e+00]]
At iteration 200 matrix is:
[[ 6.02911192e+000 -1.57546140e+000 -7.92037449e-001]
 [ 4.48987577e-129 -1.44538274e+000 -4.80637377e-001]
 [-8.50239544e-130  4.63077647e-001  1.41627082e+000]]
At iteration 250 matrix is:
[[ 6.02911192e+000 -1.47856699e+000 -9.60854622e-001]
 [ 2.55001485e-161 -1.40869640e+000 -7.93905348e-001]
 [-1.58599025e-162  1.49809676e-001  1.37958448e+000]]
At iteration 300 matrix is:
[[ 6.02911192e+000 -1.44284639e+000 -1.013704

In [67]:
np.diagonal(A_eig)

array([ 6.02911192, -1.36536824,  1.33625632])

---

8. Get the eigenvalues and eigenvectors for the matrix 𝐴
 in problem 4 using the Python built-in function

In [68]:
eigvals, eigvecs = np.linalg.eig(A)

print('Eigenvalues: ')
print(eigvals)

print('='*50)

print('Eigenvectors: ')
print(eigvecs)
print('='*50)


Eigenvalues: 
[ 6.02911192  1.33625596 -1.36536788]
Eigenvectors: 
[[-0.47185751 -0.88987496 -0.42138925]
 [-0.58896955  0.45081499 -0.29617582]
 [-0.65609859  0.0699171   0.85715284]]


Bonus: How to get question 7 closer to convergance

In [69]:
a = np.sort(eigvals)
a

array([-1.36536788,  1.33625596,  6.02911192])

In [70]:
b = np.sort(np.diagonal(A_eig))
b

array([-1.36536824,  1.33625632,  6.02911192])

In [71]:
np.round(np.abs(a - b).sum(), 7)

7e-07

This will take lots of iterations as we will use a very very small tolerance level for each of the three eigenvalues

In [72]:
tol = 0.000000000001
A_eig = A.copy()
prev_val = np.zeros(3)
iter = 1

while True:
  Q, R = np.linalg.qr(A_eig)
  A_eig = R @ Q

  if (iter + 1) % 100 == 0:
    print(f'At iteration {iter + 1} matrix is:')
    print(A_eig)
    print('='*50)

  if np.abs(np.diagonal(A_eig) - prev_val).sum() < tol:
    break

  prev_val = np.diagonal(A_eig)
  iter += 1

print(f'Total iterations to full convergence: {iter}')
print('Final matrix:')
print(A_eig)

At iteration 100 matrix is:
[[ 6.02911192e+00 -3.30379243e-01  1.73212341e+00]
 [-3.45694831e-64  3.64784196e-01  1.85151088e+00]
 [ 4.94037353e-64  9.07795854e-01 -3.93896116e-01]]
At iteration 200 matrix is:
[[ 6.02911192e+000 -1.25129956e+000  1.24243767e+000]
 [-1.95624099e-128 -1.16380720e+000  1.32424472e+000]
 [ 3.44026853e-129  3.80529693e-001  1.13469528e+000]]
At iteration 300 matrix is:
[[ 6.02911192e+000 -1.40451955e+000  1.06617390e+000]
 [-6.31739506e-193 -1.34698310e+000  9.93374798e-001]
 [ 1.33669652e-194  4.96597744e-002  1.31787118e+000]]
At iteration 400 matrix is:
[[ 6.02911192e+000 -1.42176130e+000  1.04307083e+000]
 [-1.99811961e-257 -1.36331982e+000  9.49537768e-001]
 [ 4.92296401e-260  5.82274372e-003  1.33420790e+000]]
At iteration 500 matrix is:
[[ 6.02911192e+000 -1.42374765e+000  1.04035792e+000]
 [-6.32404027e-322 -1.36513169e+000  9.44390649e-001]
 [ 0.00000000e+000  6.75625125e-004  1.33601977e+000]]
At iteration 600 matrix is:
[[ 6.02911192e+00  1.42397

In [73]:
np.sort(np.diagonal(A_eig))

array([-1.36536788,  1.33625596,  6.02911192])

In [74]:
np.sort(eigvals)

array([-1.36536788,  1.33625596,  6.02911192])